### ISSUE TITLE
Allow paralleltest setting "ignoreloopVar"

### ISSUE THREAD

**Issue by yolocs** [golangci/golangci-lint#4511] opened 2024-03-15 04:49 UTC
### Your feature request related to a problem? Please describe.

Per Go 1.22 (tip.golang.org/doc/go1.22), reinitialize loop (range) variable is no longer needed. https://github.com/kunwardeep/paralleltest has merged [PR](https://github.com/kunwardeep/paralleltest/pull/35) to add setting `ignoreloopVar` to ignore this check. But the setting is not yet available from golangci-lint setting (see: https://github.com/golangci/golangci-lint/blob/master/jsonschema/golangci.jsonschema.json#L2143).

### Describe the solution you'd like.

Support `paralleltest` `ignoreloopVar` setting

### Describe alternatives you've considered.

N/A

**Comment by ldez** [comment] 2024-03-15 13:23
duplicate of #4405

**Closed by ldez** 2024-03-15 13:23 UTC
Labels: duplicate
