### ISSUE TITLE
Let's discuss about the deprecation of `enable-all`

### ISSUE THREAD

**Issue by ldez** [golangci/golangci-lint#1888] opened 2021-04-04 21:14 UTC
**Is your feature request related to a problem? Please describe.**

@jirfag in #803 said:

> `enable-all` has the following advantage:
> 
>   1. convenient for users, I understand it.
>   2. all newly added linters are automatically used by a lot of users.
> 
> 
> But it has the following downside: when `golangci-lint` is updated users typically get some new linters enabled: it can be annoying, it can fail CI builds. Users should disable linters one by one in such cases.
> 
> I think long-term updates cost is more important than a one-time configuration cost.
> 
> Let's discuss it!

https://github.com/golangci/golangci-lint/pull/803#issuecomment-540663265

but there was no discussion, the PR was just merged.

**Describe the solution you'd like**

I would like to open a constructive debate about this deprecation.

**Describe alternatives you've considered**

Removes the deprecation of `enable-all`.

**Additional context**

https://github.com/golangci/golangci-lint/issues/1686

**Comment by frederikhors** [comment] 2021-04-04 21:23
I agree with you and I opened https://github.com/golangci/golangci-lint/discussions/1887 because I don't know how to auto-update (not manually, error-prone) new linters in my config.

**Comment by ldez** [comment] 2021-04-04 21:24
I think that the deprecation was related to Golangci-lint service and CI.

Now, Golangci-lint service is down.

The main problem of `enable-all` is for people that use `latest` in their CI because locally I think there is no real problem.

IMO the real bad practice is to use `latest` in a CI, I think most of us know this sentence: _friends don't let friends use `latest`_.

**Comment by ldez** [comment] 2021-04-04 21:41
Also the linters them-self evolve and can either introduce new rules or update their rules.
Then even if you enable only some linters you still have a possibility to break your CI.
`enable-all` is just a specific case of this problem.

So IMO, the solution is still the same: don't use `latest` in a CI and use an explicit version of the tools that run in a CI.

**Comment by ldez** [comment] 2021-04-04 21:51
From what I can see in #803, #1686, and this issue, nobody seems to want the removal of `enable-all`.

Maybe I am missing some use-cases, so please express your voice if you have a use-case that can justify this removal.

We will wait, for the moment I don't know how long, but we will take the time for the debate.

**Comment by frederikhors** [comment] 2021-04-04 21:57
In my day to day work I need something warns me about mistakes. If I upgrade it I trust that something has changed for the better and that more mistakes of mine can be detected.

If I know that I don't care about some linter I can comment out it in my config.yml.

Am I wrong in thinking like this?

**Comment by butuzov** [comment] 2021-04-05 02:23
Oh... please not. I can't dedicate much time to development (in last two months at least), and having `enable-all`  is saving me time to check what's are new linters and their settings once the new version released, and not tracking each merged pr or setting in code.

**Comment by ldez** [comment] 2021-04-05 09:46
@butuzov `enable-all` is deprecated since 2019 -> #803

This issue is to discuss and maybe remove this deprecation.

**Comment by butuzov** [comment] 2021-04-05 14:45
Sorry, i am OK to remove deprecation. Not the other way..

**Comment by Zamiell** [comment] 2021-05-15 12:02
> In my day to day work I need something warns me about mistakes. If I upgrade it I trust that something has changed for the better and that more mistakes of mine can be detected.
> If I know that I don't care about some linter I can comment out it in my config.yml.

This is exactly my thinking as well. Consider the case of Bob:

- Bob decides to integrate `golangci-lint` into his Go project with the disable-all workflow.
- Bob researches every single `golangci-lint` linter included in the project. He compiles an exhaustive list of every linter that could possibly have to do with his code base, and then includes that in his config.
- Bob is very happy with `golangci-lint`. Time passes.
- 6 months later, as his program grows, Bob decides to add SQL functionality into his program.
- Bob makes the common mistake of forgetting to close a `sql.Rows`, causing a disastrous failure in production that causes Bob to be fired.
- Later on, Bob finds that there is actually a linter rule for this: `sqlclosecheck`, which is automatically included in `golangci-lint`. It's just that when Bob did his initial evaluation, he skipped over it, because his program didn't have any SQL in it.
- Bob resolves to always use the enable-all workflow going forward.

**Comment by frederikhors** [comment] 2021-05-15 12:48
@Zamiell I'm Bob.

**Comment by Zamiell** [comment] 2021-05-15 13:10
Condolences.

**Comment by bconway** [comment] 2021-05-15 15:22
While I doubt we really need more support of `--enable-all` in this thread, the use case I have used multiple times is as follows:

- CI is set up with golangci-lint with specific linters/versions and is strictly enforced.
- My development environment uses `--enable-all` to find new, useful linters as they are introduced. I keep a `-D` list that I accumulate and then wipe out every few releases of golangci-lint, and then start the evaluation cycle over.

**Comment by ldez** [comment] 2021-05-15 16:40
After ~40 days, we still have 0 voice to remove that flag.

Please express your voice if you have a use-case that can justify the removal of `--enable-all`.

I think we will wait until the end of May or the beginning of June.

**Comment by bombsimon** [comment] 2021-05-17 06:22
As I remember it, @jirfag is one of very few who wanted to deprecate the flag which was met with disappointment from users already back in 2019 when this was first mentioned. As for my opinion I want to keep the flag to be able to use `enable-all` for local development.

I can't imagine who would have a CI pipeline of such high importance this would be an issue but still automatically bumps version of `golangci-lint` (which is required for this to be an issue) and uses `enable-all`. It sounds like an extremely unlikely use case and probably nothing for the maintainers of `golangci-lint` to consider.

**Comment by philoserf** [comment] 2021-05-26 19:25
`--enable-all`, which was a choice, was a feature. That is informed us each time something changed in any of the supported linters was a feature. Most arguments I have seen in support of its removal come down to use cases for which `--enable-all` was the wrong choice. Let's emphasize that word **_choice_**. Removing `--enable-all` does not fix improper use of the tool in CI. I see folks getting it wrong because they are operating at the limits of their understanding.

**Comment by ernado** [comment] 2021-05-27 06:15
This flag is useful for some cases like discovering new linters, so I don't want it to be removed until there is an alternative.
However, it still should not be used in examples and we should encourage users to explicitly specify enabled linters to reduce confusion while upgrading to new version.

Probably we can find a better solution that will do both things, allowing people to discover new useful linters and still not adding too much false-positives or conflicting linters? This can be some sort of managed linter preset, but it requires separate discussion and a bit off-topic.

**Comment by ldez** [comment] 2021-06-02 01:15
After 2 months, the time has come to open a PR: #2039

:tada: :tada: :tada: :rocket:

**Closed** 2021-06-02 15:04 UTC
Labels: enhancement

**Comment by Antonboom** [comment] 2025-02-10 13:08
+1 for 

> My development environment uses --enable-all to find new, useful linters as they are introduced

and 

> This flag is useful for some cases like discovering new linters, so I don't want it to be removed until there is an alternative.

Looks like separate feature request for v2 like

```go
golangci-lint diff v1.65.0

new linters:
- linter (description)

deprecated:
- linter (reason)
- ...
```

I do not use enable-all, because it kills "reproducible builds" approach, but every time use `golangci-lint linters` and try to find difference between my current config :)
