### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by rittneje** [golangci/golangci-lint#3336] opened 2022-10-31 17:04 UTC
### Welcome

- [ ] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [ ] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

I know this is from an older version, but this is the first time I've ever seen this bug. Even if we upgrade I don't know how long it might take to reproduce. Also, I cannot share the full output as it is way too big for GitHub.

```
[2022-10-31T16:36:10.534Z] fatal error: concurrent map writes
[2022-10-31T16:36:10.534Z] 
[2022-10-31T16:36:10.534Z] goroutine 10843 [running]:
[2022-10-31T16:36:10.534Z] runtime.throw({0x109e1c5?, 0xf88280?})
[2022-10-31T16:36:10.534Z] 	runtime/panic.go:992 +0x71 fp=0xc003519ad0 sp=0xc003519aa0 pc=0x4377f1
[2022-10-31T16:36:10.534Z] runtime.mapassign_faststr(0xf04c60?, 0xc0056070e0?, {0xc001fa8ca3, 0xa})
[2022-10-31T16:36:10.534Z] 	runtime/map_faststr.go:212 +0x39c fp=0xc003519b38 sp=0xc003519ad0 pc=0x4135dc
[2022-10-31T16:36:10.534Z] github.com/mgechev/revive/rule.(*UnhandledErrorRule).Apply(0xc00072c070, 0xc004a57a80, {0xc004a7ec60, 0x3, 0x0?})
[2022-10-31T16:36:10.534Z] 	github.com/mgechev/revive@v1.2.1/rule/unhandled-error.go:29 +0x1e7 fp=0xc003519ba0 sp=0xc003519b38 pc=0xd32a67
[2022-10-31T16:36:10.534Z] github.com/mgechev/revive/lint.(*File).lint(0x9c4b54?, {0xc001451400, 0x25, 0x40}, {0x1, 0x3fe999999999999a, {0xc001fa8740, 0x7}, 0x0, 0xc004a7e870, ...}, ...)
[2022-10-31T16:36:10.534Z] 	github.com/mgechev/revive@v1.2.1/lint/file.go:105 +0x19b fp=0xc003519f08 sp=0xc003519ba0 pc=0xcfa4bb
[2022-10-31T16:36:10.534Z] github.com/mgechev/revive/lint.(*Package).lint.func1(0xc007f18910?)
[2022-10-31T16:36:10.534Z] 	github.com/mgechev/revive@v1.2.1/lint/package.go:173 +0x85 fp=0xc003519fc8 sp=0xc003519f08 pc=0xcfdf25
[2022-10-31T16:36:10.534Z] github.com/mgechev/revive/lint.(*Package).lint.func2()
[2022-10-31T16:36:10.534Z] 	github.com/mgechev/revive@v1.2.1/lint/package.go:175 +0x2a fp=0xc003519fe0 sp=0xc003519fc8 pc=0xcfde6a
[2022-10-31T16:36:10.534Z] runtime.goexit()
[2022-10-31T16:36:10.534Z] 	runtime/asm_amd64.s:1571 +0x1 fp=0xc003519fe8 sp=0xc003519fe0 pc=0x469781
[2022-10-31T16:36:10.534Z] created by github.com/mgechev/revive/lint.(*Package).lint
[2022-10-31T16:36:10.534Z] 	github.com/mgechev/revive@v1.2.1/lint/package.go:172 +0xac
[2022-10-31T16:36:10.534Z] 
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.46.2 built from a3336890 on 2022-05-17T11:51:30Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
run:
  deadline: 5m
output:
  format: line-number
  print-issued-lines: false
  print-linter-name: true
linters-settings:
  gocritic:
    enabled-checks:
    - assignOp
    - boolExprSimplify
    - captLocal
    - caseOrder
    - commentFormatting
    - commentedOutCode
    - commentedOutImport
    - defaultCaseOrder
    - docStub
    - dupArg
    - dupBranchBody
    - dupSubExpr
    - emptyStringTest
    - nilValReturn
    - octalLiteral
    - sloppyLen
    - sloppyReassign
    - stringXbytes
    - weakCond
    - yodaStyleExpr
    settings:
      captLocal:
        paramsOnly: false
  misspell:
    locale: US
  nakedret:
    max-func-lines: 0
  revive:
    ignore-generated-header: true
    severity: warning
    rules:  # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
    - name: atomic
    - name: bare-return
    - name: blank-imports
    - name: bool-literal-in-expr
    - name: call-to-gc
    - name: confusing-results
    - name: constant-logical-expr
    - name: context-as-argument
    - name: context-keys-type
    - name: deep-exit
    - name: dot-imports
    - name: early-return
    - name: empty-block
    - name: error-naming
    - name: error-return
    - name: error-strings
    - name: errorf
    - name: exported
    - name: identical-branches
    - name: increment-decrement
    - name: indent-error-flow
    - name: range-val-in-closure
    - name: range-val-address
    - name: receiver-naming
    - name: redefines-builtin-id
    - name: string-of-int
    - name: struct-tag
    - name: time-naming
    - name: var-naming
    - name: var-declaration
    - name: unconditional-recursion
    - name: unexported-return
    - name: unhandled-error
      arguments:
      - fmt.Println
      - fmt.Printf
      - fmt.Print
    - name: unnecessary-stmt
    - name: unreachable-code
    - name: unused-receiver
    - name: waitgroup-by-value
linters:
  disable-all: true
  enable:
  - bodyclose
  - gocritic
  - golint
  - govet
  - ineffassign
  - misspell
  - nakedret
  - prealloc
  - revive
  - structcheck
  - unconvert
  - unused
  - varcheck
issues:
  exclude-use-default: false
  exclude-rules:
  - text: "don't use underscores in Go names"
    linters:
    - golint
    - revive
  max-issues-per-linter: 0
  max-same-issues: 0
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.18.2 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.2"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build894046258=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment] 2022-10-31 17:42
Hello,

As you said it's an old version (v1.46.2) and an old version of revive (v1.2.1).

Without a reproducible context, it's impossible to diagnose or fix.

So I will close this issue, because:
- no reproducible context
- it's impossible to know if the problem is still here in the latest version
- it seems to be a bug inside revive

**Closed by ldez** 2022-10-31 17:42 UTC
Labels: bug, won't fix
