### ISSUE TITLE
nearly 30gb memory usage on mac ios 

### ISSUE THREAD

**Issue by kurupgokul-mable** [golangci/golangci-lint#5012] opened 2024-09-13 06:25 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

![image](https://github.com/user-attachments/assets/2afdc9fb-91b0-435b-890b-625f3a760041)

### Version of golangci-lint

na

### Configuration

na

### Go environment

na

### Verbose output of running

na

### A minimal reproducible example or link to a public repository

na

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment] 2024-09-13 11:32
You provided 0 information, so I will close this issue.

Duplicate of all the issues about go1.23, you should use golangci-lint >= v1.60 compiled with go1.23.

**Closed by ldez** 2024-09-13 11:32 UTC
Labels: question
