### ISSUE TITLE
Error when try to install new version golangci

### ISSUE THREAD

**Issue by ZakhN** [golangci/golangci-lint#966] opened 2020-02-11 09:50 UTC
When i try to download and install latest version of golangci,  i get an error :
`curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.6
golangci/golangci-lint crit uname_os_check 'Linux' got converted to 'Linlx' which is not a GOOS value. Please file bug at https://github.com/client9/shlib
`
It seems like .sh script misspell name of my os, but when i execute that script in terminal its output is correct:

<pre><font color="#4E9A06"><b>nikolaj@ubuntu-laptop</b></font>:<font color="#3465A4"><b>~</b></font><font color="#CC0000"><b> </b></font>$ uname_os() {
&gt;   os=$(uname -s | tr &apos;[:upper:]&apos; &apos;[:lower:]&apos;)
&gt;   case &quot;$os&quot; in
&gt;     cygwin_nt*) os=&quot;windows&quot; ;;
&gt;     mingw*) os=&quot;windows&quot; ;;
&gt;     msys_nt*) os=&quot;windows&quot; ;;
&gt;   esac
&gt;   echo &quot;$os&quot;
&gt; }
<font color="#4E9A06"><b>nikolaj@ubuntu-laptop</b></font>:<font color="#3465A4"><b>~</b></font><font color="#CC0000"><b> </b></font>$ os=$(uname_os)
<font color="#4E9A06"><b>nikolaj@ubuntu-laptop</b></font>:<font color="#3465A4"><b>~</b></font><font color="#CC0000"><b> </b></font>$ echo $os
linux</pre>

<summary>version v1.17.1</summary>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
# run:
  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - vendor$
    - testdata$

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gas
    #- gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

# options for analysis running
run:

  # which files to skip: they will be analyzed, but issues from them
  # won't be reported. Default value is empty list, but there is
  # no need to include all autogenerated files, we confidently recognize
  # autogenerated files. If it's not please let us know.
  skip-files:
    - "^.*\\_test\\.go$"

linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 110
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 50
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 140
    # tab width in spaces. Default to 1.
    tab-width: 4
  wsl:
    # If true append is only allowed to be cuddled if appending value is
    # matching variables, fields or types on line above. Default is true.
    strict-append: true
    # Allow calls and assignments to be cuddled as long as the lines have any
    # matching variables, fields or types. Default is true.
    allow-assign-and-call: true
    # Allow multiline assignments to be cuddled. Default is true.
    allow-multiline-assign: true
    # Allow declarations (var) to be cuddled.
    allow-cuddle-declarations: true
    # Allow trailing comments in ending of blocks
    allow-trailing-comment: true
    # Force newlines in end of case at this limit (0 = never).
    force-case-trailing-whitespace: 0

issues:
  exclude:
    - composites
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
# go version go1.12.16 linux/amd64
GOARCH="amd64"
GOBIN="/home/nikolaj//home/nikolaj/go/bin"
GOCACHE="/home/nikolaj/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/nikolaj/go"
GOPROXY=""
GORACE=""
GOROOT="/snap/go/5245"
GOTMPDIR=""
GOTOOLDIR="/snap/go/5245/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/nikolaj/s7-agent-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build951966838=/tmp/go-build -gno-record-gcc-switches"
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint run -v
# INFO [config_reader] Config search paths: [./ /home/nikolaj/s7-agent-go /home/nikolaj /home /] 
INFO [config_reader] Used config file .golangci.yml 
ERRO Running error: no such linter "dogsled"      
INFO Memory: 2 samples, avg is 68.9MB, max is 68.9MB 
INFO Execution took 68.719689ms
```

</details>

**Comment by ernado** [comment] 2020-04-21 22:44
Please provide a repro, e.g. docker image.
Can't reproduce :(

**Comment by SVilgelm** [comment] 2020-07-12 22:55
Looks like the issue is resolved. Closing

**Closed by SVilgelm** 2020-07-12 22:55 UTC
Labels: area: install, feedback required, invalid

**Comment by lesiw** [comment] 2024-10-25 00:26
I can reproduce this when trying to execute the script using `busybox` v1.30.1. The root cause is that character classes like `[:upper:]` and `[:lower:]` aren't supported by all versions of `tr`. Because "u" is part of the first argument passed to `tr`, and "l" is at the same offset in the second argument, busybox `tr` replaces the "u" in Linux with "l," leading to an invalid OS. The more portable way to do a lowercase transform would be `tr A-Z a-z`.

The only workaround I can find for now is performing a `go install` of `golangci-lint`, which I know is not encouraged.

**Comment by ldez** [comment] 2024-10-25 02:07
I don't reproduce that:

```console
$ docker run --rm -it busybox:1.30.1
/ # uname -s | tr '[:upper:]' '[:lower:]'
linux
/ # echo linux | tr '[:upper:]' '[:lower:]'
linux
/ # echo Linux | tr '[:upper:]' '[:lower:]'
linux
/ # echo LINUX | tr '[:upper:]' '[:lower:]'
linux
/ # 
```

But Busybox v1.30.1 has a TLS problem:
```console
$ docker run --rm -it busybox:1.30.1
/ # wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.61.0
Connecting to raw.githubusercontent.com (185.199.109.133:443)
wget: note: TLS certificate validation not implemented
-                    100% |**********************************************************************************************************************************************************************************************************************| 11591  0:00:00 ETA
golangci/golangci-lint info checking GitHub for tag 'v1.61.0'
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer
golangci/golangci-lint crit unable to find 'v1.61.0' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
/ # 
```

No TLS problem with v1.36.1

```console
$ docker run --rm -it busybox:1.36  
Unable to find image 'busybox:1.36' locally
1.36: Pulling from library/busybox
Digest: sha256:c230832bd3b0be59a6c47ed64294f9ce71e91b327957920b6929a0caa8353140
Status: Downloaded newer image for busybox:1.36
/ # wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.61.0
Connecting to raw.githubusercontent.com (185.199.110.133:443)
wget: note: TLS certificate validation not implemented
writing to stdout
-                    100% |**********************************************************************************************************************************************************************************************************************| 11591  0:00:00 ETA
written to stdout
golangci/golangci-lint info checking GitHub for tag 'v1.61.0'
wget: note: TLS certificate validation not implemented
golangci/golangci-lint info found version: 1.61.0 for v1.61.0/linux/amd64
wget: note: TLS certificate validation not implemented
wget: note: TLS certificate validation not implemented
golangci/golangci-lint info installed ./bin/golangci-lint
/ # 
```
