### ISSUE TITLE
zsh: killed  golangci-lint run --fix -c .golangci.yml

### ISSUE THREAD

**Issue by dvwright** [golangci/golangci-lint#3620] opened 2023-02-21 04:49 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

I have a macOS and just upgraded to `Ventura 13.2.1`

Previously, the following command would complete as expected, now it dies before completing.
```
golangci-lint run --fix -c .golangci.yml
zsh: killed     golangci-lint run --fix -c .golangci.yml
```

Versions:
go version go 1.20.1 darwin/arm64 (installed via package manager `g`)
golangci-lint 1.51.2  (installed via `brew`)

Things I've tried.
```
xcode-select --install
brew install diffutils
brew update
brew upgrade
brew doctor
```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
golangci-lint has version v1.50.1 built from (unknown, mod sum: "h1:C829clMcZXEORakZlwpk7M4iDw2XiwxxKaG504SZ9zY=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# paste output here
run:
    timeout: 2m
output:
    format: colored-line-number
linters-settings:
    golint:
        min_confidence: 0.8
        set_exit_status: 1
    gofmt:
        simplify: false
linters:
    disable-all: true
    enable:
        - revive
        - gofmt
        - govet

```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
go version go1.20.1 darwin/arm64
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/davidw/Library/Caches/go-build"
GOENV="/Users/davidw/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/davidw/go/pkg/mod"
GOOS="darwin"
GOPATH="/Users/davidw/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/davidw/.go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/davidw/.go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20.1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/davidw/Code/go-packages/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/yy/psjc79914db5slhy_dwpyzvw0000gn/T/go-build1276173777=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
golangci-lint run -v
INFO [config_reader] Config search paths: [./ /Users/davidw/Code/go-packages /Users/davidw/Code /Users/davidw /Users /]
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 3 linters: [gofmt govet revive]
INFO [loader] Go packages loading at mode 575 (deps|name|types_sizes|compiled_files|exports_file|files|imports) took 1.400191041s
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 60.265542ms
zsh: killed     golangci-lint run -v
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
// is private repo...
```

</details>

**Comment by dvwright** [comment] 2023-02-21 04:52
update, I tried `run -v` again and it progressed further.
```
[davidw~/Code/go-packages(1027)]$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /Users/davidw/Code/go-packages /Users/davidw/Code /Users/davidw /Users /]
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 3 linters: [gofmt govet revive]
INFO [loader] Go packages loading at mode 575 (types_sizes|compiled_files|deps|exports_file|files|imports|name) took 1.185543583s
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 57.190334ms
INFO Memory: 479 samples, avg is 58090.7MB, max is 78414.4MB
INFO Execution took 2m0.176666041s
zsh: killed     golangci-lint run -v
```

**Comment by ldez** [comment] 2023-02-21 08:20
duplicate of #3609, #3582, #3565, #3549, #3538, #3536, #3535, #3533, #3470

**Closed by ldez** 2023-02-21 08:20 UTC
Labels: bug

**Comment by dvwright** [comment] 2023-03-22 05:09
FWIW, this fixed it for me.
```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.0
```
From message,
```
Warning: golangci/tap/golangci-lint 1.52.1 already installed
if you encounter problem with golangci-lint on armv mac1, install it using
this command: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.0
```
