### ISSUE TITLE
new linter deadcode

### ISSUE THREAD

**Issue by phanirithvij** [golangci/golangci-lint#4876] opened 2024-07-23 01:25 UTC
### Welcome

- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Your feature request related to a problem? Please describe

https://go.dev/blog/deadcode

### Describe the solution you'd like

Add support for this new tool as a linter.

### Describe alternatives you've considered

I've searched for that term in the code and found a deprecated linter with the same name which was something else entirely.

### Supporter

- [ ] I am a sponsor through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldez** [comment] 2024-07-23 02:11
duplicate of #4254, #4298, #4270, 4383

**Closed by ldez** 2024-07-23 02:11 UTC
Labels: duplicate

**Comment by phanirithvij** [comment] 2024-07-23 03:36
I'm sorry 😞
