### ISSUE TITLE
Add Misspell linter support

### ISSUE THREAD

**Issue by dixonwille** [golangci/golangci-lint#107] opened 2018-06-14 22:17 UTC
https://github.com/client9/misspell

Unsure how easy/hard this will be but it would be nice to be able to have this linter. Even if it is disabled by default.

**Comment by jirfag** [comment] 2018-06-15 05:52
It’s a duplicate of https://github.com/golangci/golangci-lint/issues/100

**Closed by jirfag** 2018-06-15 05:52 UTC
