### ISSUE TITLE
nolint directive removal leaves whitespace behind

### ISSUE THREAD

**Issue by scop** [golangci/golangci-lint#4384] opened 2024-02-14 10:45 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

When a `//nolint` directive is being removed as part of an automatic fix, undesirable whitespace -- empty lines, or trailing whitespace -- gets left behind.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.56.1 built with go1.22.0 from a25592b5 on 2024-02-08T18:03:33Z
```

</details>

### Configuration

<details>

```console
--enable=nolintlint --fix
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
package main

import "fmt"

//nolint
func main() {
	fmt.Println("Hello, world!") //nolint
}
```
</details>

The fix leaves an empty line behind where the top level `//nolint` was on line 5, and a trailing whitespace after `)` where the inline `//nolint`  was on line 7. Both the empty line and the trailing whitespace should be removed.

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

**Comment by ldez** [comment] 2024-02-14 12:52
Hello,

Due to a change of go fmt inside go1.19.
We have to enforce the directive style.

The syntax of directives is: `[a-zA-Z]+:[a-zA-Z].*`.

`//nolint` should be replaced by `//nolint:all`.

https://golangci-lint.run/usage/false-positives/#nolint-directive

duplicate of #3554, #3109,#3098, #3063, #3068, #3101.

**Closed by ldez** 2024-02-14 12:52 UTC
Labels: question
