### ISSUE TITLE
No go files to analyze

### ISSUE THREAD

**Issue by hazcod** [golangci/golangci-lint#865] opened 2019-11-22 08:32 UTC
Version:
```
~/Downloads/iron-redis$ $(go env GOPATH)/bin/golangci-lint version
golangci-lint has version 1.21.0 built from 645e794 on 2019-10-15T18:15:04Z
```

PoC:
```
~/Downloads/iron-redis$ ls . healthcheck/
.:
Dockerfile    README.md     healthcheck   redis.compose redis.conf

healthcheck/:
go.mod         go.sum         healthcheck.go vendor

~/Downloads/iron-redis$ $(go env GOPATH)/bin/golangci-lint run ./...
ERRO Running error: context loading failed: package github.com/go-redis/redis: no go files to analyze

~/Downloads/iron-redis$ $(go env GOPATH)/bin/golangci-lint run healthcheck/...
ERRO Running error: context loading failed: package github.com/go-redis/redis: no go files to analyze

~/Downloads/iron-redis$ $(go env GOPATH)/bin/golangci-lint run healthcheck/healthcheck.go
ERRO Running error: context loading failed: package github.com/go-redis/redis: no go files to analyze
```

**Comment by hazcod** [comment] 2019-11-25 06:45
This only happens when I do not have a `go.mod` in the root of my repository.
Creating a foo `go.mod` and having the rest in the subdirectory does not work.

**Comment by hazcod** [comment] 2019-11-26 22:03
I fixed it by running the linter in the subdirectory: https://github.com/reviewdog/action-golangci-lint/pull/15

**Comment by fdcds** [comment] 2020-02-13 18:24
Probably a duplicate of #825.

**Comment by kazhuravlev** [comment] 2020-03-27 09:11
to fix error just

```
go get ./...
golangci-lint run
```

**Comment by jirfag** [comment] 2020-05-18 07:50
Duplicate of #825

**Closed** 2020-05-18 07:50 UTC
Labels: bug
