### ISSUE TITLE
goland latest plugin error

### ISSUE THREAD

**Issue by SandQuattro** [golangci/golangci-lint#3870] opened 2023-06-02 08:57 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

after download new version from tools -> Go linter -> Get Latest

java.lang.Exception: Failed to Discover Linters: RunProcessResult(returnCode=3, stdout=, stderr=level=error msg="[linter] depguard: create analyzer: couldn't expand $gostd: could not read GOROOT directory: open src: no such file or directory\nmust have an Allow and/or Deny package list"
)
	at com.ypwang.plugin.UtilitiesKt.parseLinters(Utilities.kt:99)
	at com.ypwang.plugin.form.GoLinterConfigurable.lambda$initializeLinters$14(GoLinterConfigurable.java:387)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.53.0 built with go1.20.4 from 9f2528a3 on 2023-06-01T19:43:45Z
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
dont have
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by MutatePat** [comment] 2023-06-02 09:05
We're getting this on our CI - this issue is not golang specific

**Comment by ldez** [comment] 2023-06-02 09:05
duplicate of #3862

**Closed by ldez** 2023-06-02 09:05 UTC
Labels: duplicate
