### ISSUE TITLE
Ability to pass the top level run.go version to other linters

### ISSUE THREAD

**Issue by scop** [golangci/golangci-lint#2680] opened 2022-03-24 09:58 UTC
### Your feature request related to a problem? Please describe.

If one wants to configure all linters for specific go version, as well as golangci-lint itself, multiple settings need to be changed and maintained.

### Describe the solution you'd like.

It would be great if there was a possibility to make linters "inherit" the top level run.go version. It would be even greater now with the automatic detection support; chances are that a specific version would not be needed anywhere in golangci-lint's config, everything would just follow from `go.mod`.

Currently, if one wants to configure for example 1.18 all the way, 1.18 needs to be separately configured for
- [gofumpt](https://golangci-lint.run/usage/linters#gofumpt)
- [gosimple](https://golangci-lint.run/usage/linters#gosimple)
- [staticcheck](https://golangci-lint.run/usage/linters#staticcheck)
- [stylecheck](https://golangci-lint.run/usage/linters#stylecheck)

There are not that many things this setting affects in linters currently, but there are some, and I guess there will be more.

#### A special sentinel value for triggering inheritance

The mentioned linters could have a special sentinel value that would trigger inheriting the run.go version, for example `inherit`, or `run.go`.

```yaml
linters-settings:
  gofumpt:
    lang-version: "inherit"
  gosimple:
    go: "inherit"
  staticcheck:
    go: "inherit"
  stylecheck:
    go: "inherit"
```

#### Make inheritance the default

Inheriting by default would be my personal preference, but I guess we've been quite conservative in changing the default versions passed to linters traditionally, so this might be a bit much.

**Comment by ldez** [comment] 2022-03-24 10:04
duplicate of #2158

**Closed by ldez** 2022-03-24 10:04 UTC
Labels: enhancement
