### ISSUE TITLE
Revive: cannot trigger rule "exported"

### ISSUE THREAD

**Issue by mattysweeps** [golangci/golangci-lint#2263] opened 2021-09-28 21:40 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

I cannot trigger the "exported" rule of the `revive` linter. Note: I think there might be more rules which are untriggerable, but I've tested and provided an example for the "exported" rule.

### Version of golangci-lint

<details>

```console
$ golangci-lint version
golangci-lint has version 1.42.1 built from 54f4301d on 2021-09-06T17:05:10Z
```

</details>

### Configuration file

I've tried with no `.golangci.yml` config at all, no `revive` config, and the full config below:

<details>

```console
$ cat .golangci.yml
linters:
  enable:
    - revive
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters-settings:
  revive:
    ignore-generated-header: true
    severity: error
    confidence: 0.1
    error-code: -1
    warning-code: -1
    rules:
    - name: exported
```

</details>

### Go environment

<details>

```console
$ go version
go version go1.17.1 linux/amd64
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

Running revive by itself works on the example:
```
$ revive
example.go:5:1: exported function MyExample should have comment or be unexported
```

<details>

https://play.golang.org/p/yAMJITL7uBT

```go
package example

import "fmt"

func MyExample() {
        fmt.Println("this function needs a comment")
}
```

</details>

**Comment by ldez** [comment] 2021-09-28 22:56
Duplicate of #2114, #1937

**Closed by ldez** 2021-09-28 22:56 UTC
Labels: duplicate, question
