### ISSUE TITLE
internal compiler error: have package "main" want package "..."

### ISSUE THREAD

**Issue by tsaarni** [golangci/golangci-lint#3583] opened 2023-02-10 07:58 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

After upgrading to go1.20 typecheck results in compiler error for `tools.go` file. The file is following a common pattern described [here](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module). 

The error looks like following

```
tools.go:1: : # example.com/tools
<unknown line number>: internal compiler error: have package "main" (0xc00043b9a0), want package "github.com/onsi/ginkgo/v2/ginkgo" (0xc00043b900)

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new (typecheck)
//go:build tools
```

See the code example below to reproduce the error.

Possibly related to https://github.com/golang/go/issues/54542

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.51.1 built from (unknown, mod sum: "h1:N5HD/x0ZrhJYsgKWyz7yJxxQ8JKR0Acc+FOP7QtGSAA=") on (unknown)
```

</details>

### Configuration file

<details>
No configuration file.
</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.20 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tsaarni/.cache/go-build"
GOENV="/home/tsaarni/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tsaarni/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tsaarni/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/tsaarni/sdk/go1.20"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/tsaarni/sdk/go1.20/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/tsaarni/package/tools/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3751123669=/tmp/go-build -gno-record-gcc-switches"```
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```console


mkdir tools
cd tools

go mod init example.com/tools

cat > tools.go <<EOF
//go:build tools

package tools

// nolint:typecheck
import _ "github.com/onsi/ginkgo/v2/ginkgo"
EOF

go get github.com/onsi/ginkgo/v2/ginkgo

golangci-lint run --build-tags=tools
```

</details>

**Comment by ldez** [comment] 2023-02-10 08:11
Hello,

It is the same expected behavior as `go build`:

```console
$ go build -tags=tools .
tools.go:6:8: import "github.com/onsi/ginkgo/v2/ginkgo" is a program, not an importable package
```

**Comment by tsaarni** [comment] 2023-02-10 08:32
Thank you for your response @ldez. I have modified the issue description a bit.  Originally, it included also

```
tools.go:5:8: import "github.com/onsi/ginkgo/v2/ginkgo" is a program, not an importable package (typecheck)
```

but that error can be removed by adding `// nolint:typecheck` like shown in the code example.

The error that I'm reporting is

```
tools.go:1: : # example.com/tools
<unknown line number>: internal compiler error: have package "main" (0xc00042b9f0), want package "github.com/onsi/ginkgo/v2/ginkgo" (0xc00042b950)

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new (typecheck)
//go:build tools
```

**Comment by ldez** [comment] 2023-02-10 08:43
`typecheck` is not a real linter but a way to catch compilation errors.

Note: The directive `// nolint:typecheck` must not have spaces after `//`: -> `//nolint:typecheck`. But even like that the directive will not be applied because the error reported by typecheck cannot be ignored.

**Comment by tsaarni** [comment] 2023-02-10 08:50
Ah, sorry my mistake! Thank you for clarification.

However, any use of `nolint` removes `not an importable package` error, while the internal compiler error remains. The compiler error is possibly related to https://github.com/golang/go/issues/54542.

**Comment by ldez** [comment] 2023-02-10 08:52
It doesn't seem related to this issue.

**Comment by tsaarni** [comment] 2023-02-10 08:53
Ok, my guess was purely based on similar error mentioned there

```
<unknown line number>: internal compiler error: have package "lie" (0xc0003dd130), want package "a" (0xc0003dcfa0)
```

**Comment by ldez** [comment] 2024-03-22 00:50
The problem seems fixed now:

```console
$ docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.57.0 golangci-lint run --build-tags=tools
$
```

**Closed by ldez** 2024-03-22 00:50 UTC
Labels: question
