### ISSUE TITLE
Show a summary total issues on the CLI

### ISSUE THREAD

**Issue by silverwind** [golangci/golangci-lint#3374] opened 2022-11-23 21:28 UTC
### Your feature request related to a problem? Please describe.

It would be nice if `golangci-lint` cli could show a summary of how many issues it found and if possible, also show how many of them are fixable via `--fix`.

### Describe the solution you'd like.

A summary at the end of the CLI run, similar to `eslint`:

```
✖ 39 problems (26 errors, 13 warnings)
  0 errors and 1 warning potentially fixable with the `--fix` option.
```

### Additional context.

Maybe the summary should not be printed unless the issue limit is unrestricted as the number might be confusing otherwise. Thought I do think showing all issues should be the default configuration.

```yaml
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
```

**Comment by ldez** [comment] 2022-11-23 21:33
Duplicate of #2924

**Closed by ldez** 2022-11-23 21:33 UTC
Labels: enhancement
