### ISSUE TITLE
nolint by linter rule

### ISSUE THREAD

**Issue by peakle** [golangci/golangci-lint#2706] opened 2022-03-30 19:31 UTC
### Your feature request related to a problem? Please describe.

is some case i don't want to disable all linter checks for expression by `nolint:gocritic` but only one rule `hugeParam` for example

### Describe the solution you'd like.

add feature to write nolint directive for specific rule i propose the following syntax: `nolint:linter_name:check_name` as example `nolint:gocritic:hugeParam`

### Describe alternatives you've considered.

~

**Comment by sebastien-rosset** [comment] 2022-11-15 20:16
For the `gocritic` example, there are three possible levels: `gocritic:ruleguard:ruleguard-rule-name`.
Ruleguard is a powerful checker under `gocritic`, and within ruleguard it's possible to have hundreds of checks.

**Comment by denisvmedia** [comment] 2023-08-31 09:26
As for `revive`, it actually supports Its own ignore comments, but there're not parsed by `golangci-lint`. I'm wondering if we can have an API (or a convention) for the linters to support so that they can themselves ignore according to the ignore rule from golangci-lint.

I can volunteer the PR, but before starting with it we need to have a clear vision on how we want to achieve it.

**Comment by ldez** [comment] 2023-08-31 12:37
Related to #1658

**Comment by ldez** [comment] 2024-03-21 22:15
Duplicate of #1165

**Closed by ldez** 2024-03-21 22:15 UTC
Labels: enhancement, area: nolint
