### ISSUE TITLE
Add "nilaway" as a linter

### ISSUE THREAD

**Issue by Dentrax** [golangci/golangci-lint#4045] opened 2023-08-28 07:22 UTC
### Your feature request related to a problem? Please describe.

NilAway is a static analysis tool that seeks to help developers avoid nil panics in production by catching them at compile time rather than runtime.

### Describe the solution you'd like.

https://github.com/uber-go/nilaway

### Describe alternatives you've considered.

`-`

### Additional context.

IIUC, nilaway is more like a "tool" rather than a linter.

/cc @yuxincs @zzqatuber

**Comment by ldez** [comment] 2023-08-28 09:42
In order for a pull request adding a linter to be reviewed, the linter and the PR must follow some requirements.

- [ ] The CLA must be signed

### Pull Request Description

- [ ] It must have a link to the linter repository.
- [ ] It must provide a short description of the linter.

### Linter

- [ ] It must not be a duplicate of another linter or a rule of a linter. (the team will help to verify that)
- [ ] It must have a valid license (AGPL is not allowed) and the file must contain the required information by the license, ex: author, year, etc.
- [ ] The linter repository must have a CI and tests.
- [ ] It must use [`go/analysis`](https://golangci-lint.run/contributing/new-linters/).
- [ ] It must have a valid tag, ex: `v1.0.0`, `v0.1.0`.
- [ ] It must not contain `init()`.
- [ ] It must not contain `panic()`.
- [ ] It must not contain `log.fatal()`, `os.exit()`, or similar.
- [ ] It must not modify the AST.
- [ ] It must not have false positives/negatives. (the team will help to verify that)
- [ ] It must have tests inside golangci-lint.

### The Linter Tests Inside Golangci-lint

- [ ] They must have at least one std lib import.
- [ ] They must work with `T=<name of the linter test file>.go make test_linters`. (the team will help to verify that)

### `.golangci.reference.yml`

- [ ] The linter must be added to the list of available linters (alphabetical case-insensitive order).
    - `enable` and `disable` options
- [ ] If the linter has a configuration, the exhaustive configuration of the linter must be added (alphabetical case-insensitive order)
    - The values must be different from the default ones.
    - The default values must be defined in a comment.
    - The option must have a short description.

### Others Requirements

- [ ] The files (tests and linter) inside golangci-lint must have the same name as the linter.
- [ ] The `.golangci.yml` of golangci-lint itself must not be edited and the linter must not be added to this file.
- [ ] The linters must be sorted in the alphabetical order (case-insensitive) in the `Manager.GetAllSupportedLinterConfigs(...)` and `.golangci.reference.yml`.
- [ ] The load mode (`WithLoadMode(...)`):
    - if the linter doesn't use types: `goanalysis.LoadModeSyntax`
    - `goanalysis.LoadModeTypesInfo` required `WithLoadForGoAnalysis()` in the `Manager.GetAllSupportedLinterConfigs(...)`
- [ ] The version in `WithSince(...)` must be the next minor version (`v1.X.0`) of golangci-lint.
- [ ] `WithURL()` must contain the URL of the repository.

### Recommendations

- [ ] The linter should not use SSA. (SSA can be a problem with generics)
- [ ] The linter repository should have a readme and linting.
- [ ] The linter should be published as a binary. (useful to diagnose bug origins)

---

The golangci-lint team will edit this comment to check the boxes before and during the review.

The code review will start after the completion of those checkboxes (except for the specific items that the team will help to verify).

If the author of the PR is a member of the golangci-lint team, he should not edit this message.

**This checklist does not imply that we will accept the linter.**

**Comment by Dentrax** [comment] 2023-08-28 10:41
Ah, good to know. Maybe devs of that tool can optimize the code base to provide a linter interface.

Just curious to ask, why don't you provide a some kind of _feature gate_ to allow "tools" and "false positives"? I totally understand your "golangci-lint's criteria". But maybe you can define "linter graduation policy": alpha > beta > stable, etc. So enabling experimental gates could allow non-stable and false-positive tools/linters.

I know, this would be a part of totally different proposal to discuss more about.

**Comment by ldez** [comment] 2023-08-28 10:51
> Maybe devs of that tool can optimize the code base to provide a linter interface.

This is not the problem: the problem is false positives, not the linter interface.

> Just curious to ask, why don't you provide a some kind of feature gate to allow "tools" and "false positives"? I totally understand your "golangci-lint's criteria". But maybe you can define "linter graduation policy": alpha > beta > stable, etc. So enabling experimental gates could allow non-stable and false-positive tools/linters.

The goal of golangci-lint is to be accurate, i.e. no false positives, this is why we have default exclusions.
So, for now, there is no possibility of "false-positive linter" or "potential issues detector".

**Closed** 2023-08-28 23:26 UTC
Labels: declined

**Comment by karelbilek** [comment] 2023-11-19 20:16
I don't fully understand this policy, when golangci-lint has style linters which are all very "potential issue detectors" and have lot of "false positives", but, it's up to you I guess

**Comment by YishaiBerg** [comment] 2023-11-21 19:15
Why not just mention the problems in the documentation and allow devs the choice of whether to use it or not? Why opinionated over flexible?

**Comment by dolmen** [comment] 2023-11-22 14:45
@karelbilek `nilaway` is still quite young and has really too many false positives. Just have a look at its [issues queue](https://github.com/uber-go/nilaway/issues).

**Comment by mfreeman451** [comment] 2023-11-22 16:48
Why can't it just be added outside of the default set -- something people would enable if they wanted?

**Comment by moogacs** [comment] 2024-02-27 14:14
I've created a [custom plugin](https://github.com/moogacs/nilaway-plugin) to be used locally and in GHA

**Comment by karelbilek** [comment] 2024-02-27 15:07
(I have horrible experience with using plugins, because you need to keep tracking all the versions, and it produces inscrutable error messages when things go wrong. But, if it helps anyone... good)

**Comment by moogacs** [comment] 2024-02-27 15:11
yeah i can tell :D , but i've considered that in that plugin and the script with it should be able to detect the dependancies version and force it before building it

**Comment by yuxincs** [comment] 2024-02-27 15:18
> (I have horrible experience with using plugins, because you need to keep tracking all the versions, and it produces inscrutable error messages when things go wrong. But, if it helps anyone... good)

I agree. I have proposed an alternative way for integrating private linters from learnings of caddy the web server written in Go: https://github.com/golangci/golangci-lint/issues/2505#issuecomment-1963021714 which makes it easier to build a single custom binary (with the private linter code). Not sure if golangci-lint folks will like it 😃 

If we have to build a plugin, we're happy to add some logic (e.g., the `New` function) to make it easier to build NilAway as a plugin.

**Comment by mfreeman451** [comment] 2024-02-27 15:22
> > (I have horrible experience with using plugins, because you need to keep tracking all the versions, and it produces inscrutable error messages when things go wrong. But, if it helps anyone... good)
> 
> I agree. I have proposed an alternative way for integrating private linters from learnings of [caddy the web server](https://github.com/caddyserver/caddy) written in Go: [#2505 (comment)](https://github.com/golangci/golangci-lint/issues/2505#issuecomment-1963021714) which makes it easier to build a single custom binary (with the private linter code). Not sure if golangci-lint folks will like it 😃
> 
> If we _have to_ build a plugin, we're happy to add some logic (e.g., the `New` function) to make it easier to build NilAway as a plugin.

Somewhat related - https://github.com/golang/go/issues/63290
