### ISSUE TITLE
/root/go/pkg/mod/github.com/golangci/golangci-lint@v1.33.0/pkg/golinters/gci.go:50:25: assignment mismatch: 3 variables but gci.Run returns 2 values

### ISSUE THREAD

**Issue by charnet1019** [golangci/golangci-lint#1523] opened 2020-11-24 04:08 UTC
go version：1.14.12

go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
go: downloading github.com/golangci/golangci-lint v1.33.0
go: found github.com/golangci/golangci-lint/cmd/golangci-lint in github.com/golangci/golangci-lint v1.33.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/go-xmlfmt/xmlfmt v0.0.0-20191208150333-d5b6f63a941b
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/sirupsen/logrus v1.7.0
go: downloading github.com/spf13/viper v1.7.1
go: downloading github.com/fatih/color v1.10.0
go: downloading golang.org/x/tools v0.0.0-20201124005743-911501bfb504
go: downloading github.com/sonatard/noctx v0.0.1
go: downloading github.com/jirfag/go-printf-func-name v0.0.0-20200119135958-7558a9eaa5af
go: downloading github.com/uudashr/gocognit v1.0.1
go: downloading github.com/Djarvur/go-err113 v0.1.0
go: downloading github.com/sourcegraph/go-diff v0.6.1
go: downloading github.com/golangci/unconvert v0.0.0-20180507085042-28b1c447d1f4
go: downloading github.com/jingyugao/rowserrcheck v0.0.0-20191204022205-72ab7603b68a
go: downloading github.com/moricho/tparallel v0.2.1
go: downloading github.com/polyfloyd/go-errorlint v0.0.0-20201102195345-32ea8681d64b
go: downloading github.com/golangci/check v0.0.0-20180506172741-cfe4005ccda2
go: downloading github.com/mitchellh/mapstructure v1.3.3
go: downloading github.com/golangci/gofmt v0.0.0-20190930125516-244bba706f1a
go: downloading github.com/spf13/cast v1.3.1
go: downloading github.com/securego/gosec/v2 v2.5.0
go: downloading github.com/ryanrolds/sqlclosecheck v0.3.0
go: downloading github.com/shazow/go-diff v0.0.0-20160112020656-b6b7b6733b8c
go: downloading mvdan.cc/gofumpt v0.0.0-20201123090407-3077abae40c0
go: downloading github.com/timakin/bodyclose v0.0.0-20200424151742-cb6215831a94
go: downloading github.com/spf13/cobra v1.1.1
go: downloading github.com/golangci/prealloc v0.0.0-20180630174525-215b22d4de21
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading honnef.co/go/tools v0.0.1-2020.1.6
go: downloading github.com/magiconair/properties v1.8.4
go: downloading github.com/tomarrell/wrapcheck v0.0.0-20200820102009-a737f1327799
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/matoous/godox v0.0.0-20200801072554-4fb83dc2941e
go: downloading github.com/tdakkota/asciicheck v0.0.0-20200416200610-e657995f937b
go: downloading github.com/golangci/lint-1 v0.0.0-20191013205115-297bf364a8e0
go: downloading github.com/go-critic/go-critic v0.5.2
go: downloading github.com/google/go-cmp v0.5.3
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading golang.org/x/mod v0.3.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/maratori/testpackage v1.0.1
go: downloading github.com/golangci/errcheck v0.0.0-20181223084120-ef45e06d44b6
go: downloading github.com/ssgreg/nlreturn/v2 v2.1.0
go: downloading mvdan.cc/unparam v0.0.0-20200501210554-b37ab49443f7
go: downloading github.com/golangci/revgrep v0.0.0-20180812185044-276a5c0a1039
go: downloading github.com/spf13/afero v1.4.1
go: downloading 4d63.com/gochecknoglobals v0.0.0-20201008074935-acfc0b28355a
go: downloading github.com/gofrs/flock v0.8.0
go: downloading github.com/golangci/maligned v0.0.0-20180506175553-b1d89398deca
go: downloading github.com/kisielk/gotool v1.0.0
go: downloading github.com/kunwardeep/paralleltest v1.0.2
go: downloading github.com/go-toolsmith/astcast v1.0.0
go: downloading github.com/tetafro/godot v1.3.0
go: downloading golang.org/x/text v0.3.4
go: downloading github.com/golangci/ineffassign v0.0.0-20190609212857-42439a7714cc
go: downloading github.com/tommy-muehle/go-mnd v1.3.1-0.20200224220436-e6f9a994e8fa
go: downloading github.com/subosito/gotenv v1.2.0
go: downloading github.com/golangci/go-misc v0.0.0-20180628070357-927a3d87b613
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/stretchr/testify v1.6.1
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/OpenPeeDeeP/depguard v1.0.1
go: downloading github.com/golangci/gocyclo v0.0.0-20180528144436-0a533e8fa43d
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/quasilyte/go-ruleguard v0.2.1
go: downloading golang.org/x/sys v0.0.0-20201119102817-f84b799fce68
go: downloading github.com/pelletier/go-toml v1.8.1
go: downloading github.com/quasilyte/regex/syntax v0.0.0-20200805063351-8f842688393c
go: downloading github.com/denis-tingajkin/go-header v0.3.1
go: downloading github.com/go-toolsmith/strparse v1.0.0
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/go-toolsmith/astfmt v1.0.0
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/go-toolsmith/astcopy v1.0.0
go: downloading github.com/daixiang0/gci v0.2.5
go: downloading github.com/go-toolsmith/astp v1.0.0
go: downloading github.com/kyoh86/exportloopref v0.1.8
go: downloading github.com/ryancurrah/gomodguard v1.1.0
go: downloading github.com/golangci/dupl v0.0.0-20180902072040-3e9179ac440a
go: downloading github.com/gostaticanalysis/analysisutil v0.6.1
go: downloading github.com/gobwas/glob v0.2.3
go: downloading github.com/golangci/misspell v0.3.5
go: downloading github.com/go-toolsmith/typep v1.0.2
go: downloading github.com/jgautheron/goconst v0.0.0-20201117150253-ccae5bf973f3
go: downloading github.com/nishanths/exhaustive v0.1.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20200615113413-eeeca48fe776
go: downloading github.com/go-toolsmith/astequal v1.0.0
go: downloading github.com/ultraware/whitespace v0.0.4
go: downloading github.com/gostaticanalysis/comment v1.4.1
go: downloading github.com/ultraware/funlen v0.0.3
go: downloading github.com/phayes/checkstyle v0.0.0-20170904204023-bfd46e6a821d
go: downloading github.com/stretchr/objx v0.3.0
go: downloading mvdan.cc/interfacer v0.0.0-20180901003855-c20040233aed
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading github.com/mbilski/exhaustivestruct v1.1.0
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading github.com/nakabonne/nestif v0.3.0
go: downloading github.com/bombsimon/wsl/v3 v3.1.0
go: downloading mvdan.cc/lint v0.0.0-20170908181259-adc824a0674b
go: downloading gopkg.in/ini.v1 v1.62.0
go: downloading github.com/nbutton23/zxcvbn-go v0.0.0-20180912185939-ae427f1e4c1d
go: golang.org/x/tools upgrade => v0.0.0-20201124005743-911501bfb504
go: golang.org/x/sys upgrade => v0.0.0-20201119102817-f84b799fce68
go: gopkg.in/yaml.v2 upgrade => v2.3.0
go: github.com/stretchr/testify upgrade => v1.6.1
go: golang.org/x/text upgrade => v0.3.4
go: github.com/fatih/color upgrade => v1.10.0
go: github.com/mattn/go-colorable upgrade => v0.1.8
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
go: github.com/davecgh/go-spew upgrade => v1.1.1
go: golang.org/x/mod upgrade => v0.3.0
go: github.com/spf13/afero upgrade => v1.4.1
go: github.com/google/go-cmp upgrade => v0.5.3
go: github.com/magiconair/properties upgrade => v1.8.4
go: github.com/mitchellh/mapstructure upgrade => v1.3.3
go: github.com/spf13/pflag upgrade => v1.0.5
go: github.com/sirupsen/logrus upgrade => v1.7.0
go: github.com/go-toolsmith/typep upgrade => v1.0.2
go: honnef.co/go/tools upgrade => v0.0.1-2020.1.6
go: github.com/gostaticanalysis/analysisutil upgrade => v0.6.1
go: github.com/mattn/go-isatty upgrade => v0.0.12
go: github.com/fsnotify/fsnotify upgrade => v1.4.9
go: github.com/spf13/jwalterweatherman upgrade => v1.1.0
go: gopkg.in/ini.v1 upgrade => v1.62.0
go: github.com/pkg/errors upgrade => v0.9.1
go: github.com/pelletier/go-toml upgrade => v1.8.1
go: github.com/gostaticanalysis/comment upgrade => v1.4.1
go: github.com/stretchr/objx upgrade => v0.3.0
go: github.com/quasilyte/regex/syntax upgrade => v0.0.0-20200805063351-8f842688393c
go: github.com/mitchellh/go-homedir upgrade => v1.1.0
go: github.com/spf13/cast upgrade => v1.3.1
go: github.com/quasilyte/go-ruleguard upgrade => v0.2.1
go: github.com/polyfloyd/go-errorlint upgrade => v0.0.0-20201102195345-32ea8681d64b
go: github.com/timakin/bodyclose upgrade => v0.0.0-20200424151742-cb6215831a94
go: gopkg.in/yaml.v3 upgrade => v3.0.0-20200615113413-eeeca48fe776
go: github.com/golangci/revgrep upgrade => v0.0.0-20180812185044-276a5c0a1039
go: github.com/tomarrell/wrapcheck upgrade => v0.0.0-20200820102009-a737f1327799
go: github.com/spf13/viper upgrade => v1.7.1
go: mvdan.cc/gofumpt upgrade => v0.0.0-20201123090407-3077abae40c0
go: github.com/Djarvur/go-err113 upgrade => v0.1.0
go: github.com/matoous/godox upgrade => v0.0.0-20200801072554-4fb83dc2941e
go: github.com/jirfag/go-printf-func-name upgrade => v0.0.0-20200119135958-7558a9eaa5af
go: github.com/golangci/misspell upgrade => v0.3.5
go: github.com/daixiang0/gci upgrade => v0.2.5
go: github.com/tdakkota/asciicheck upgrade => v0.0.0-20200416200610-e657995f937b
# github.com/golangci/golangci-lint/pkg/golinters
/root/go/pkg/mod/github.com/golangci/golangci-lint@v1.33.0/pkg/golinters/gci.go:50:25: assignment mismatch: 3 variables but gci.Run returns 2 values

**Comment by bombsimon** [comment] 2020-11-24 07:16
Duplicate of #1518 and #1506.

As mentioned in https://golangci-lint.run/usage/install/, go get is not supported.

> Note: such go get installation aren't guaranteed to work. We recommend using binary installation.

**Closed by bombsimon** 2020-11-24 07:16 UTC
Labels: bug

**Comment by ernado** [comment] 2020-11-24 13:49
`go get` should work in general, but `go get -u` is definitely not supported because it will update all dependencies and ignore pinned versions in go.mod, which is unfortunate
