### ISSUE TITLE
Add autofix for gci

### ISSUE THREAD

**Issue by barweiss** [golangci/golangci-lint#2604] opened 2022-02-20 14:25 UTC
### Your feature request related to a problem? Please describe.

We were using the GCI linter to enforce import order. However, with the 1.44.2 update, it seems like auto-fix support was dropped.
This change makes it harder to enforce import order as the developer has to manually fix the code.

### Describe the solution you'd like.

It seems like GCI supports write mode. Using it for auto fix could be possible.

### Describe alternatives you've considered.

Removing the GCI linter as it is currently unusable, or downgrading golangci-lint.

**Comment by ldez** [comment] 2022-02-20 14:49
kind of duplicate of #2591

**Comment by barweiss** [comment] 2022-02-20 14:58
Yea, sorry, I missed the closed issue.
I see that you closed it due to GCI not supporting autofix, however, it seems like the "write" command does fix the import order.

**Comment by barweiss** [comment] 2022-02-20 15:00
Anyway, I may be out of line here, but even though GCI is not a responsibility of the golangci-lint team, this change affects everyone that uses the GCI linter and relied on the autofix behavior.
I would suggest downgrading GCI specifically if possible until this issue is sorted (perhaps allowing the newer version to be used or evaded using the configuration).

**Closed** 2022-05-30 17:51 UTC
Labels: enhancement
