### ISSUE TITLE
Improve nolint comments matching

### ISSUE THREAD

**Issue by jakubtomany** [golangci/golangci-lint#68] opened 2018-06-05 17:25 UTC
Match nolint comments:
- on a line above the problematic code
- on a line above the function definition containing the problematic code
- if there are spaces in comment between `nolint:` and linters list

**Comment by jirfag** [comment] 2018-06-06 19:10
thank you for the issue, it's a duplicate of https://github.com/golangci/golangci-lint/issues/65, let's continue in it

**Closed by jirfag** 2018-06-06 19:10 UTC
Labels: enhancement
