### ISSUE TITLE
private linter support for autofix

### ISSUE THREAD

**Issue by ashanbrown** [golangci/golangci-lint#2565] opened 2022-02-13 14:11 UTC
### Your feature request related to a problem? Please describe.

Private linters can't enable autofix

### Describe the solution you'd like.

A way to set autofix, and really all config settings for a custom linter.  A custom linter is also currently assumed to be fast and to need typo info.  Is there any reason we can't expose these controls in the custom linter setting?

### Describe alternatives you've considered.

Running my custom linter outside of golangci lint.

### Additional context.

See [the code](https://github.com/golangci/golangci-lint/blob/32cf48edc90e1c5ac21aa6d0ad21bd0dc9fcdf39/pkg/lint/lintersdb/manager.go#L735) for where we set up custom linters.

**Comment by ldez** [comment] 2022-02-13 14:16
Related to #1779

**Comment by ashanbrown** [comment] 2022-02-13 14:31
I didn't realize that we weren't ready to apply `SuggestedFixes`.  LMK if I can help.

**Comment by ldez** [comment] 2023-06-04 12:35
duplicate of #1728

**Closed by ldez** 2023-06-04 12:35 UTC
Labels: enhancement, linter: custom
