### ISSUE TITLE
ERRO Running error: context loading failed: no go files to analyze

### ISSUE THREAD

**Issue by laizhiwei123** [golangci/golangci-lint#1855] opened 2021-03-17 08:11 UTC
I can't use golangci-lint run to traverse the. Go file of the sub folder. The project has a go mod file. I can run golangci run in the directory of the sub project

![Uploading 截图录屏_选择区域_20210317161001.png…]()
![Uploading 截图录屏_选择区域_20210317161034.png…]()

**Comment by ldez** [comment] 2021-03-17 08:51
duplicate of #825

FYI your image links don't work

**Closed by ldez** 2021-03-17 08:51 UTC
Labels: bug
