### ISSUE TITLE
Memory usage more than 80GB

### ISSUE THREAD

**Issue by bastengao** [golangci/golangci-lint#3582] opened 2023-02-10 07:30 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

I execute `golangci-lint run`, the memory usage is more than 80GB

golangci-lint was installed from brew

<img width="1165" alt="截屏2023-02-10 15 27 45" src="https://user-images.githubusercontent.com/785335/218029681-1c599f6a-ffbe-4c49-adbe-ad93b1bd5062.png">

### Version of golangci-lint

golangci-lint has version 1.51.0 built from 6d3f06c on 2023-02-02T08:18:45Z

### Configuration file

run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive

### Go environment

<details>
go version go1.20 darwin/arm64
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/bastengao/Library/Caches/go-build"
GOENV="/Users/bastengao/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/bastengao/go/pkg/mod"
GONOPROXY="git.rtw.team/rtwteam/backend"
GONOSUMDB="git.rtw.team/rtwteam/backend"
GOOS="darwin"
GOPATH="/Users/bastengao/go"
GOPRIVATE="git.rtw.team/rtwteam/backend"
GOPROXY="https://proxy.golang.com.cn,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.20"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/bastengao/works/teacup/teacupapi/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/qs/jk5lkxd10dv6bb9ftq6y_xbh0000gn/T/go-build3764237982=/tmp/go-build -gno-record-gcc-switches -fno-common"
</details>

### Verbose output of running

<details>
INFO [config_reader] Config search paths: [./ /Users/bastengao/works/teacup/teacupapi /Users/bastengao/works/teacup /Users/bastengao/works /Users/bastengao /Users /]
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 8 linters: [errcheck gosimple govet ineffassign revive staticcheck typecheck unused]
INFO [loader] Go packages loading at mode 575 (exports_file|files|imports|compiled_files|deps|types_sizes|name) took 1.631643541s
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 39.280833ms
[1]    18538 killed     golangci-lint run -v
</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment] 2023-02-10 07:34
duplicate of #3565

Brew uses go1.19 instead of go1.20.
https://github.com/golangci/golangci-lint/issues/3565#issuecomment-1418001980

So you have to use either our binaries or our Docker image or build/install golangci-lint with go1.20.

golangci-lint requires to be built with go1.20,  without that golangci-lint cannot work with go1.20.

Note the latest version of golangci-lint is `v1.51.1`.

**Closed by ldez** 2023-02-10 07:34 UTC
Labels: bug
