### ISSUE TITLE
Mirror docker image on ghcr.io

### ISSUE THREAD

**Issue by tarampampam** [golangci/golangci-lint#3621] opened 2023-02-21 07:53 UTC
### Your feature request related to a problem? Please describe.

The problem is very simple - the docker hub has a limitation for image pulling. And to solve this problem, could you mirror the docker image on `ghcr.io`?

### Describe the solution you'd like.

A CI step to push the docker image with `golangci-lint` on `ghcr.io`

### Describe alternatives you've considered.

---

**Comment by ldez** [comment] 2023-02-21 08:16
duplicate of #3105

**Closed by ldez** 2023-02-21 08:16 UTC
Labels: enhancement
