### ISSUE TITLE
configuration overlays, ability to merge config, from shared base to local exceptions

### ISSUE THREAD

**Issue by ldemailly** [golangci/golangci-lint#4895] opened 2024-08-09 23:47 UTC
### Welcome

- [X] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Your feature request related to a problem? Please describe

Problem is copy-past'ing config everywhere, a solution is to share a config and download it, which is what I do

Yet sometimes/often you'd want to make minor tweaks to said config for a specific project, cloning the source goes back to rot and diverging config and having to update dozen of files each time there is a new golangci-lint release

### Describe the solution you'd like

golangci-lint run -c base_config.yml -c deltas.yml

(obviously merging is not... that trivial and maybe additional directives are needed it's not just a yml merge, I think)

### Describe alternatives you've considered

trying to do some merging myself, maybe it's easy and worth documenting how and this is just a "doc" issue

### Supporter

- [ ] I am a sponsor through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

**Comment by ldemailly** [comment] 2024-08-09 23:48
note it's somewhat related but not the same as #1141

**Comment by ldez** [comment] 2024-08-09 23:53
duplicate of #1141

**Closed by ldez** 2024-08-09 23:53 UTC
Labels: enhancement

**Comment by ldemailly** [comment] 2024-08-10 00:06
well it's related but not the same but sure...

**Comment by ldez** [comment] 2024-08-10 00:09
https://github.com/golangci/golangci-lint/issues/1141#issuecomment-1679730383
