### ISSUE TITLE
Linters that depends on "diff" will not work on windows out of the box

### ISSUE THREAD

**Issue by Ahumayed** [golangci/golangci-lint#2451] opened 2022-01-03 09:00 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

I am writing code on my windows machine (using VS Code). And as far as I knew the linting was working fine for the most part.
However, when I pushed my code, our pipeline did it's own linting on a linux environment and it will show some linting issues that do not show on my machine (i.e. dupl, funlen, lll and structcheck).

I installed golangci-lint by choosing it on VS Code Go extension settings and it prompt me to install golangci-lint.

As can be seen in the verbose output, a warning was printed related to diff tool:
`level=warning msg="[runner] Can't run linter goanalysis_metalinter: gofmt: error computing diff: exec: \"diff\": executable file not found in %PATH%"`

After a bit of googling I found this stackoverflow question: [https://stackoverflow.com/questions/56206562/why-gofmt-d-gives-computing-diff-exec-diff-executable-file-not-found-in](url)

And as suggested, I added the git binaries to my path and tried again and it is working now exactly like the server's linter.

I am not sure what can be done here to avoid this issue for other windows users, but I think it would be very useful if diff was automatically bundled with the linter packages or maybe a more verbose warning with steps to fix should be shown so the users can know easily that not all linters are working.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.43.0 built from (unknown, mod sum: "h1:SLwZFEmDgopqZpfP495zCtV9REUf551JJlJ51Ql7NZA=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# https://github.com/golangci/golangci/wiki/Configuration

service:
  golangci-lint-version: 1.38.0 # use the fixed version to not introduce new linters unexpectedly

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: go.quarapay.dev/svc/kycintegrations
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: go.quarapay.dev/svc/kycintegrations
  gomnd:
    settings:
      mnd:
        checks: # don't include the "operation" and "assign"
          - argument
          - case
          - condition
          - return
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - exportloopref
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  # don't enable:
  # - asciicheck
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: main\.go
      linters:
        - funlen
        - lll
    - path: _test\.go
      linters:
        - dupl
        - gomnd
        - funlen
        - gocyclo
        - lll
#    - path: internal/api/errors.go
#      linters:
#        - gocyclo
#        - funlen
#    - path: internal/service/job/rescheduler.go
#      linters:
#        - gomnd

run:
  timeout: 5m
  skip-dirs:
    - tilt_modules

```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.17.5 windows/amd64
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\abdulrahman.humayed\AppData\Local\go-build
set GOENV=C:\Users\abdulrahman.humayed\AppData\Roaming\go\env  
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\abdulrahman.humayed\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\abdulrahman.humayed\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.5
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\abdulrahman.humayed\Documents\Code\svc-kycintegrations\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ABDULR~1.HUM\AppData\Local\Temp\go-build2564171896=/tmp/go-build -gno-record-gcc-switches 
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
level=info msg="[config_reader] Config search paths: [./ C:\\Users\\abdulrahman.humayed\\Documents\\Code\\svc-kycintegrations C:\\Users\\abdulrahman.humayed\\Documents\\Code C:\\Users\\abdulrahman.humayed\\Documents 
C:\\Users\\abdulrahman.humayed C:\\Users C:\\]"
level=info msg="[config_reader] Used config file .golangci.yml"
level=info msg="[lintersdb] Active 35 linters: [bodyclose deadcode depguard dogsled dupl errcheck exportloopref funlen gochecknoinits goconst gocritic gocyclo gofmt goimports gomnd goprintffuncname gosec gosimple govet ineffassign lll misspell nakedret nolintlint revive rowserrcheck staticcheck structcheck stylecheck typecheck unconvert unparam unused varcheck whitespace]"
level=info msg="[loader] Go packages loading at mode 575 (types_sizes|compiled_files|name|files|imports|deps|exports_file) took 751.8925ms"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 1.0131ms"
level=info msg="[linters context/goanalysis] analyzers took 56.3432106s with top 10 stages: gocritic: 19.8288606s, buildir: 16.3496679s, fact_deprecated: 2.2967061s, ctrlflow: 1.8988604s, printf: 1.8183178s, nilness: 1.7780382s, the_only_name: 1.6068497s, inspect: 1.4987689s, buildssa: 1.3422505s, fact_purity: 1.1962256s" 
level=warning msg="[runner] Can't run linter goanalysis_metalinter: gofmt: error computing diff: exec: \"diff\": executable file not found in %PATH%"
level=info msg="[runner] processing took 0s with stages: exclude: 0s, max_same_issues: 0s, severity-rules: 0s, sort_results: 0s, cgo: 0s, skip_files: 0s, identifier_marker: 0s, max_per_file_from_linter: 0s, source_code: 0s, path_prefixer: 0s, path_prettifier: 0s, skip_dirs: 0s, nolint: 0s, max_from_linter: 0s, autogenerated_exclude: 0s, exclude-rules: 0s, uniq_by_line: 0s, filename_unadjuster: 0s, diff: 0s, path_shortener: 0s"  
level=info msg="[runner] linters took 13.230339s with stages: goanalysis_metalinter: 13.2287515s"
level=info msg="File cache stats: 33 entries of total size 76.7KiB"
level=info msg="Memory: 142 samples, avg is 597.0MB, max is 845.7MB"
level=info msg="Execution took 14.0366188s"
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by bombsimon** [comment] 2022-01-03 09:09
Duplicate of #362

**Closed by bombsimon** 2022-01-03 09:09 UTC
Labels: bug
