### ISSUE TITLE
goimportssort support

### ISSUE THREAD

**Issue by capricornusx** [golangci/golangci-lint#4283] opened 2023-12-23 17:00 UTC
### Your feature request related to a problem? Please describe.

`Goimports` will not categorize your imports when wrongly formatted. PRs to add in the functionality [were denied](https://github.com/golang/tools/pull/68#issuecomment-450897493) .

https://github.com/AanZee/goimportssort

### Describe the solution you'd like.

Please add `goimportssort` to our project.

### Describe alternatives you've considered.

Manual install :)

### Additional context.

- Automatically split your imports in three categories: inbuilt, external and local.
- Written fully in Golang, no dependencies, works on any platform.
- Detects Go module name automatically.
- Orders your imports alphabetically.
- Removes additional line breaks.
-  No more manually fixing import orders.

**Comment by Antonboom** [comment] 2023-12-23 17:19
Duplicate of https://golangci-lint.run/usage/linters/#gci

**Comment by capricornusx** [comment] 2023-12-23 17:20
> Duplicate of https://golangci-lint.run/usage/linters/#gci

Thaks!

**Closed** 2023-12-23 17:21 UTC
Labels: enhancement
