### ISSUE TITLE
golangci-lint will be stuck and use huge memory in go 1.20 environment, both mac and linux.

### ISSUE THREAD

**Issue by chenyahui** [golangci/golangci-lint#3536] opened 2023-02-02 06:38 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

golangci-lint will be stuck and use huge memory in go 1.20 environment, both mac and linux.

Rollback the go version to go1.19, and golangci-lint returns to normal.

# mac
![image](https://user-images.githubusercontent.com/6067594/216248760-8c256b49-f308-4726-a738-2905f10a40e6.png)

# linux
<img width="907" alt="image" src="https://user-images.githubusercontent.com/6067594/216249315-19e69394-b8db-4650-a745-435bea5e8511.png">

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
```
golangci-lint has version v1.50.1 built from (unknown, mod sum: "h1:C829clMcZXEORakZlwpk7M4iDw2XiwxxKaG504SZ9zY=") on (unknown)
</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# paste output here
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```
Linux: go version go1.20 linux/amd64

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```
$ golangci-lint run   
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
[1]    2629 killed     golangci-lint run
</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by vitaly-eureka-security** [comment] 2023-02-02 06:50
I can confirm this happens on Windows as well

**Comment by ldez** [comment] 2023-02-02 08:13
duplicate of #3535,#3533,#3470

**Closed by ldez** 2023-02-02 08:13 UTC
Labels: bug
