### ISSUE TITLE
skip-dirs not skipping the file

### ISSUE THREAD

**Issue by mayank558** [golangci/golangci-lint#2748] opened 2022-04-06 09:24 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

I am trying to skip some directories in project from golangci-lint but using the skip-dirs is not helping

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# golangci-lint has version 1.43.0 built from 861262b on 2021-11-02T20:54:42Z

```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
run:
  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # from this option's value (see skip-dirs-use-default).
  skip-dirs:
    - <path to the file>
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.17.5 darwin/arm64
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```go
run:
  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # from this option's value (see skip-dirs-use-default).
  skip-dirs:
    - <path to the file>
```

</details>

**Comment by ldez** [comment] 2022-04-06 10:19
duplicate of #1832

**Closed by ldez** 2022-04-06 10:19 UTC
Labels: duplicate
