### ISSUE TITLE
nolint sub linter

### ISSUE THREAD

**Issue by yonderblue** [golangci/golangci-lint#4050] opened 2023-08-29 17:45 UTC
### Your feature request related to a problem? Please describe.

Cannot do nolint:revive:cyclomatic or something like that

### Describe the solution you'd like.

see above

### Describe alternatives you've considered.

ignoring too much

**Comment by ldez** [comment] 2023-08-29 19:18
Duplicate of #1658

**Closed by ldez** 2023-08-29 19:18 UTC
Labels: enhancement

**Comment by yonderblue** [comment] 2023-08-30 16:17
Does not seem to be a duplicate? I'm referring to something like https://github.com/mgechev/revive/issues/885#issuecomment-1699432511.
