### ISSUE TITLE
Disallow multiple executions on same project

### ISSUE THREAD

**Issue by sudo-suhas** [golangci/golangci-lint#167] opened 2018-07-26 08:25 UTC
**Version of golangci-lint:** e17b9543

**Go environment:**
<details>
<summary><code>go version && go env</code></summary>

```
go version go1.10.1 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/suhaskaranth/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/suhaskaranth/installs/go-tools"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build692454894=/tmp/go-build   -gno-record-gcc-switches"
```

</details>

<br>

I am using the linter using editor integration on vscode. After I did a find-replace for some 9 files(changed comments only), the system hung completely. Since I had "System Monitor" already open, I could see that there were that many instances of `golangci-lint` trying to run. Is there any way to handle this so that redundant concurrent executions don't run and kill the system?

**Comment by sudo-suhas** [comment] 2018-07-26 08:29
Relevant issue from vscode extension: Microsoft/vscode-go#1015

**Comment by jirfag** [comment] 2018-07-28 20:56
hi, thank you, but it's a duplicate of https://github.com/golangci/golangci-lint/issues/108

**Closed by jirfag** 2018-07-28 20:56 UTC
