### ISSUE TITLE
Memory Overflow(Go1.20)

### ISSUE THREAD

**Issue by lx-world** [golangci/golangci-lint#3535] opened 2023-02-02 03:01 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Go 1.20,  Memory overflow when running golangci

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.50.1 built from (unknown, mod sum: "h1:C829clMcZXEORakZlwpk7M4iDw2XiwxxKaG504SZ9zY=") on (unknown)
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
run:
  timeout: 5m
  issues-exit-code: 0
  tests: false

linters:
  enable:
    - nilerr
    - goconst
    - goprintffuncname
    - importas
    - predeclared
    - revive
    - rowserrcheck

```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.20 linux/amd64
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO [lintersdb] Active 14 linters: [errcheck goconst goprintffuncname gosimple govet importas ineffassign nilerr predeclared revive rowserrcheck staticcheck typecheck unused]

block.........................

```

</details>

### Code example or link to a public repository

<details>

```go
```

</details>

**Comment by ldez** [comment] 2023-02-02 03:11
duplicate of #3533

**Closed by ldez** 2023-02-02 03:11 UTC
Labels: duplicate
