### ISSUE TITLE
Add tool to auto-fix fieldalignment issues

### ISSUE THREAD

**Issue by frederikhors** [golangci/golangci-lint#2356] opened 2021-11-12 21:02 UTC
### Your feature request related to a problem? Please describe.

I'm using `govet` for `fieldalignment` (`maligned` was deprecated).

[Here](https://github.com/golangci/golangci-lint/discussions/2298#discussioncomment-1631196) I found out there is a tool to auto-fix those lines:

> There is a tool to detect and fix this.
> go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
> fieldalignment -fix <package_path>

### Describe the solution you'd like.

Can we add that auto tool in golangci-lint, plase?

### Describe alternatives you've considered.

Manually loose time.

**Comment by ldez** [comment] 2021-11-12 22:33
Duplicate of #1779

**Closed by ldez** 2021-11-12 22:33 UTC
Labels: enhancement
