### ISSUE TITLE
could not run linter xxx:buildssa: analysis skipped: errors in package: xxx could not import xxx

### ISSUE THREAD

**Issue by ydcool** [golangci/golangci-lint#896] opened 2019-12-25 06:51 UTC
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>

```bash
$ golangci-lint --version
golangci-lint has version 1.21.0 built from 645e794 on 2019-10-15T18:15:04Z
```

</details>

<details><summary>Config file</summary>

```bash
$ cat .golangci.yml
cat: .golangci.yml: No such file or directory
```

</details>

<details><summary>Go environment</summary>

```bash
$ go version && go env
go version go1.13.4 windows/amd64
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\yindongchao\AppData\Local\go-build
set GOENV=C:\Users\yindongchao\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=*.gitlab.com,*.gitee.com,*.inspur.com
set GONOSUMDB=*.gitlab.com,*.gitee.com,*.inspur.com
set GOOS=windows
set GOPATH=C:\Users\yindongchao\go
set GOPRIVATE=*.gitlab.com,*.gitee.com,*.inspur.com
set GOPROXY=https://goproxy.io
set GOROOT=c:\go
set GOSUMDB=off
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\YINDON~1\AppData\Local\Temp\go-build718758610=/tmp/go-build -gno-record-gcc-switches
```

</details>

<details><summary>Verbose output of running</summary>

```bash
$ golangci-lint run -v
C:\Users\yindongchao\go\bin\golangci-lint.exe run -v --disable=typecheck --enable=bodyclose --enable=dogsled --enable=gocritic --enable=gocyclo --enable=golint --enable=gosec --enable=maligned --enable=prealloc --enable=stylecheck D:\Repo\git.inspur.com\inspur-cloud\g5-storage\pkg\incloud
level=info msg="[config_reader] Config search paths: [./ D:\\Repo\\git.inspur.com\\inspur-cloud\\g5-storage\\pkg\\incloud D:\\Repo\\git.inspur.com\\inspur-cloud\\g5-storage\\pkg D:\\Repo\\git.inspur.com\\inspur-cloud\\g5-storage D:\\Repo\\git.inspur.com\\inspur-cloud D:\\Repo\\git.inspur.com D:\\Repo D:\\]"
level=info msg="[lintersdb] Active 18 linters: [bodyclose deadcode dogsled errcheck gocritic gocyclo golint gosec gosimple govet ineffassign maligned prealloc staticcheck structcheck stylecheck unused varcheck]"
level=info msg="[loader] Go packages loading at mode 575 (deps|files|imports|name|compiled_files|types_sizes|exports_file) took 1.3535824s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 2.4803ms"
level=info msg="[runner/goanalysis_metalinter/goanalysis] analyzers took 1.488ms with top 10 stages: errcheck: 496µs, buildssa: 496µs, S1011: 496µs, unreachable: 0s, ST1011: 0s, SA5009: 0s, SA4008: 0s, S1019: 0s, fact_deprecated: 0s, shift: 0s"
level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildssa: analysis skipped: errors in package: [D:\\Repo\\git.inspur.com\\inspur-cloud\\g5-storage\\pkg\\incloud\\brainkeeper.go:13:2: could not import k8s.io/client-go/kubernetes (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\kubernetes\\clientset.go:24:12: could not import k8s.io/client-go/discovery (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\discovery\\discovery_client.go:39:13: could not import k8s.io/client-go/rest (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\rest\\transport.go:24:2: could not import k8s.io/client-go/plugin/pkg/client/auth/exec (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\plugin\\pkg\\client\\auth\\exec\\exec.go:35:2: could not import golang.org/x/crypto/ssh/terminal (C:\\Users\\yindongchao\\go\\pkg\\mod\\golang.org\\x\\crypto@v0.0.0-20190923035154-9ee001bba392\\ssh\\terminal\\util_windows.go:97:36: 2-valued windows.GetCurrentProcess() (value of type (windows.Handle, error)) where single value is expected))))) D:\\Repo\\git.inspur.com\\inspur-cloud\\g5-storage\\pkg\\incloud\\brainkeeper.go:14:2: could not import k8s.io/client-go/tools/leaderelection/resourcelock (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\tools\\leaderelection\\resourcelock\\configmaplock.go:26:15: could not import k8s.io/client-go/kubernetes/typed/core/v1 (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\kubernetes\\typed\\core\\v1\\componentstatus.go:29:7: could not import k8s.io/client-go/rest (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\rest\\transport.go:24:2: could not import k8s.io/client-go/plugin/pkg/client/auth/exec (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\plugin\\pkg\\client\\auth\\exec\\exec.go:35:2: could not import golang.org/x/crypto/ssh/terminal (C:\\Users\\yindongchao\\go\\pkg\\mod\\golang.org\\x\\crypto@v0.0.0-20190923035154-9ee001bba392\\ssh\\terminal\\util_windows.go:97:36: 2-valued windows.GetCurrentProcess() (value of type (windows.Handle, error)) where single value is expected)))))]"
level=info msg="[runner/unused/goanalysis] analyzers took 0s with top 10 stages: buildssa: 0s, U1000: 0s"
level=warning msg="[runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [D:\\Repo\\git.inspur.com\\inspur-cloud\\g5-storage\\pkg\\incloud\\brainkeeper.go:13:2: could not import k8s.io/client-go/kubernetes (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\kubernetes\\clientset.go:24:12: could not import k8s.io/client-go/discovery (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\discovery\\discovery_client.go:39:13: could not import k8s.io/client-go/rest (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\rest\\transport.go:24:2: could not import k8s.io/client-go/plugin/pkg/client/auth/exec (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\plugin\\pkg\\client\\auth\\exec\\exec.go:35:2: could not import golang.org/x/crypto/ssh/terminal (C:\\Users\\yindongchao\\go\\pkg\\mod\\golang.org\\x\\crypto@v0.0.0-20190923035154-9ee001bba392\\ssh\\terminal\\util_windows.go:97:36: 2-valued windows.GetCurrentProcess() (value of type (windows.Handle, error)) where single value is expected))))) D:\\Repo\\git.inspur.com\\inspur-cloud\\g5-storage\\pkg\\incloud\\brainkeeper.go:14:2: could not import k8s.io/client-go/tools/leaderelection/resourcelock (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\tools\\leaderelection\\resourcelock\\configmaplock.go:26:15: could not import k8s.io/client-go/kubernetes/typed/core/v1 (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\kubernetes\\typed\\core\\v1\\componentstatus.go:29:7: could not import k8s.io/client-go/rest (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\rest\\transport.go:24:2: could not import k8s.io/client-go/plugin/pkg/client/auth/exec (C:\\Users\\yindongchao\\go\\pkg\\mod\\k8s.io\\client-go@v0.0.0-20190918160344-1fbdaa4c8d90\\plugin\\pkg\\client\\auth\\exec\\exec.go:35:2: could not import golang.org/x/crypto/ssh/terminal (C:\\Users\\yindongchao\\go\\pkg\\mod\\golang.org\\x\\crypto@v0.0.0-20190923035154-9ee001bba392\\ssh\\terminal\\util_windows.go:97:36: 2-valued windows.GetCurrentProcess() (value of type (windows.Handle, error)) where single value is expected)))))]"
level=info msg="[runner] processing took 0s with stages: nolint: 0s, max_per_file_from_linter: 0s, source_code: 0s, cgo: 0s, skip_files: 0s, exclude: 0s, diff: 0s, max_from_linter: 0s, max_same_issues: 0s, path_shortener: 0s, skip_dirs: 0s, identifier_marker: 0s, exclude-rules: 0s, uniq_by_line: 0s, filename_unadjuster: 0s, path_prettifier: 0s, autogenerated_exclude: 0s"
level=info msg="[runner] linters took 1.3243193s with stages: goanalysis_metalinter: 888.3358ms, unused: 435.9835ms"
level=info msg="File cache stats: 0 entries of total size 0B"
level=info msg="Memory: 30 samples, avg is 53.7MB, max is 140.3MB"
level=info msg="Execution took 2.8415811s"

Process finished with exit code 0
```

</details>

**Comment by ernado** [comment] 2020-01-07 18:45
Seems like related to #885

**Comment by ernado** [comment] 2020-02-05 18:03
@ydcool please check latest version, issue should be fixed

**Comment by ydcool** [comment] 2020-02-06 01:42
@ernado thank you, I'll try it out soon.

**Comment by diegoholiveira** [comment] 2020-02-19 16:16
I'm having the same issue.

```
ERRO Running error: asmdecl: analysis skipped: errors in package: [serviceunit.go:3:8: could not import fmt (/usr/local/Cellar/go/1.13.8/libexec/src/fmt/format.go:8:2: could not import strconv (/usr/local/Cellar/go/1.13.8/libexec/src/strconv/quote.go:11:2: could not import unicode/utf8 (/usr/local/Cellar/go/1.13.8/libexec/src/unicode/utf8/utf8.go:28:8: expected ';', found b00000000)))]
```

I'm running the latest version available in brew:

```
% brew info golangci-lint
golangci/tap/golangci-lint: stable 1.23.6
```

With Go 1.13:

```
% go version
go version go1.13.8 darwin/amd64
```

**Comment by Zhangxxamber** [comment] 2020-02-21 11:32
> 
> 
> I'm having the same issue.
> 
> ```
> ERRO Running error: asmdecl: analysis skipped: errors in package: [serviceunit.go:3:8: could not import fmt (/usr/local/Cellar/go/1.13.8/libexec/src/fmt/format.go:8:2: could not import strconv (/usr/local/Cellar/go/1.13.8/libexec/src/strconv/quote.go:11:2: could not import unicode/utf8 (/usr/local/Cellar/go/1.13.8/libexec/src/unicode/utf8/utf8.go:28:8: expected ';', found b00000000)))]
> ```
> 
> I'm running the latest version available in brew:
> 
> ```
> % brew info golangci-lint
> golangci/tap/golangci-lint: stable 1.23.6
> ```
> 
> With Go 1.13:
> 
> ```
> % go version
> go version go1.13.8 darwin/amd64
> ```
I also have this problem
$ golangci-lint --version
golangci-lint has version v1.23.6 built from b9eef79 on 2020-02-18 19:29:56
$ go version
go version go1.13.8 windows/amd64

**Comment by JuanJoseGonGi** [comment] 2020-02-23 22:36
I have the same error

**Comment by anubhabMajumdar** [comment] 2020-02-28 02:52
I am having the same issue. Any updates? I am using golangci-lint v1.23.6 and go 1.13.

**Comment by JunliWang** [comment] 2020-03-02 19:15
I had the same issue with v1.23.3 after my Go is upgraded from 1.13 to 1.14.
clean cache did not help.
But upgrading to v1.23.7 resolved my problem.

**Comment by zerkms** [comment] 2020-03-06 22:45
The same issue here: 

```
golangci-lint has version 1.23.8 built from 76a82c6 on 2020-03-04T14:29:52Z
go version go1.14 linux/amd64
```

**Comment by AntonStoeckl** [comment] 2020-03-07 22:12
Same here:

`
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/home/anton/GolandProjects/go-iddd/service/customer/application/CommandHandler.go:16:17: undeclared name: ForStoringCustomerEvents /home/anton/GolandProjects/go-iddd/service/customer/application/CommandHandler.go:19:39: undeclared name: ForStoringCustomerEvents] 
WARN [runner] Can't run linter goanalysis_metalinter: bodyclose: failed prerequisites: buildssa@command-line-arguments 
ERRO Running error: bodyclose: failed prerequisites: buildssa@command-line-arguments
`
Cache clean did not help.
Tried v1.23.6, v1.23.7, v1.23.8 with Go version 1.13.8 and v1.23.7, v1.23.8 with Go version 1.14

**Comment by diegoholiveira** [comment] 2020-03-16 19:33
I solve this issue running this command before run the `golangci-lint`: `go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null`

**Comment by gaurav-dalvi** [comment] 2020-03-25 19:05
i am getting same error for v1.24.0 as well. Any pointers?

**Comment by ernado** [comment] 2020-03-25 20:38
@gaurav-dalvi can you please provide a log?
Now it should contain details with actual reason.

**Comment by gaurav-dalvi** [comment] 2020-03-25 21:06
@ernado :
```
level=warning msg="[runner] Can't run linter goanalysis_metalinter: SA1018: failed prerequisites: 
```

**Comment by gaurav-dalvi** [comment] 2020-03-25 21:06
things are passin for me now with 1.23.8 but for sure 1.24.0 was giving above problem

**Comment by tschaub** [comment] 2020-03-25 21:11
I'm using `golangci-lint` via the Go extension for VSCode.  I think I'm seeing the same issue that others are, but am uncertain if there are other tools used by the extension that are complicating the problem.  Apologies if this is not the same issue as above.

I'm running `golangci-lint@v1.24.0`.  Below are the steps to reproduce and the output from `golangci-lint`.

```bash
mkdir example && cd example && go mod init example.com/pkg/example
touch main.go
```

In VSCode, I paste the following (without imports):
```go
package main

type Soup struct {
	Chicken bool
}

var _ json.Marshaler = (*Soup)(nil)

func (soup *Soup) MarshalJSON() ([]byte, error) {
	if soup.Chicken {
		return []byte(`"yum!"`), nil
	}
	return []byte(`"meh"`), nil
}

func main() {
	soup := &Soup{}
	data, err := json.Marshal(soup)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("soup: %s\n", string(data))
}
```
I see this output from the Go extension:
```
Starting linting the current package at /Users/tschaub/projects/example
Error while running tool: /Users/tschaub/go/bin/golangci-lint run --print-issued-lines=false
level=warning msg="[runner] Can't run linter goanalysis_metalinter: assign: failed prerequisites: [inspect@example.com/pkg/example: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:7:7: undeclared name: json /Users/tschaub/projects/example/main.go:18:15: undeclared name: json /Users/tschaub/projects/example/main.go:20:3: undeclared name: log /Users/tschaub/projects/example/main.go:22:2: undeclared name: fmt]]"
level=warning msg="[runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:7:7: undeclared name: json /Users/tschaub/projects/example/main.go:18:15: undeclared name: json /Users/tschaub/projects/example/main.go:20:3: undeclared name: log /Users/tschaub/projects/example/main.go:22:2: undeclared name: fmt]"
level=error msg="Running error: buildir: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:7:7: undeclared name: json /Users/tschaub/projects/example/main.go:18:15: undeclared name: json /Users/tschaub/projects/example/main.go:20:3: undeclared name: log /Users/tschaub/projects/example/main.go:22:2: undeclared name: fmt]"
```

After accepting the first suggested fix (import `encoding/json`), I see this output from the Go extension:
```
Starting linting the current package at /Users/tschaub/projects/example
Error while running tool: /Users/tschaub/go/bin/golangci-lint run --print-issued-lines=false
level=warning msg="[runner] Can't run linter goanalysis_metalinter: SA1025: failed prerequisites: [buildir@example.com/pkg/example: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:22:3: undeclared name: log /Users/tschaub/projects/example/main.go:24:2: undeclared name: fmt]]"
level=warning msg="[runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:22:3: undeclared name: log /Users/tschaub/projects/example/main.go:24:2: undeclared name: fmt]"
level=error msg="Running error: buildir: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:22:3: undeclared name: log /Users/tschaub/projects/example/main.go:24:2: undeclared name: fmt]"
```

At this point, the extension no longer works, and I see this "Your workspace is misconfigured" dialog.

![image](https://user-images.githubusercontent.com/41094/77585894-e09b6f00-6eaa-11ea-83b5-141c4f971a89.png)

**Comment by JuanJoseGonGi** [comment] 2020-03-26 00:50
> I'm using `golangci-lint` via the Go extension for VSCode. I think I'm seeing the same issue that others are, but am uncertain if there are other tools used by the extension that are complicating the problem. Apologies if this is not the same issue as above.
> 
> I'm running `golangci-lint@v1.24.0`. Below are the steps to reproduce and the output from `golangci-lint`.
> 
> ```shell
> mkdir example && cd example && go mod init example.com/pkg/example
> touch main.go
> code .
> ```
> 
> In VSCode, I paste the following (without imports) into `main.go`:
> 
> ```go
> package main
> 
> type Soup struct {
> 	Chicken bool
> }
> 
> var _ json.Marshaler = (*Soup)(nil)
> 
> func (soup *Soup) MarshalJSON() ([]byte, error) {
> 	if soup.Chicken {
> 		return []byte(`"yum!"`), nil
> 	}
> 	return []byte(`"meh"`), nil
> }
> 
> func main() {
> 	soup := &Soup{}
> 	data, err := json.Marshal(soup)
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	fmt.Printf("soup: %s\n", string(data))
> }
> ```
> 
> I see this output from the Go extension:
> 
> ```
> Starting linting the current package at /Users/tschaub/projects/example
> Error while running tool: /Users/tschaub/go/bin/golangci-lint run --print-issued-lines=false
> level=warning msg="[runner] Can't run linter goanalysis_metalinter: assign: failed prerequisites: [inspect@example.com/pkg/example: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:7:7: undeclared name: json /Users/tschaub/projects/example/main.go:18:15: undeclared name: json /Users/tschaub/projects/example/main.go:20:3: undeclared name: log /Users/tschaub/projects/example/main.go:22:2: undeclared name: fmt]]"
> level=warning msg="[runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:7:7: undeclared name: json /Users/tschaub/projects/example/main.go:18:15: undeclared name: json /Users/tschaub/projects/example/main.go:20:3: undeclared name: log /Users/tschaub/projects/example/main.go:22:2: undeclared name: fmt]"
> level=error msg="Running error: buildir: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:7:7: undeclared name: json /Users/tschaub/projects/example/main.go:18:15: undeclared name: json /Users/tschaub/projects/example/main.go:20:3: undeclared name: log /Users/tschaub/projects/example/main.go:22:2: undeclared name: fmt]"
> ```
> 
> After accepting the first suggested fix (import `encoding/json`), I see this output from the Go extension:
> 
> ```
> Starting linting the current package at /Users/tschaub/projects/example
> Error while running tool: /Users/tschaub/go/bin/golangci-lint run --print-issued-lines=false
> level=warning msg="[runner] Can't run linter goanalysis_metalinter: SA1025: failed prerequisites: [buildir@example.com/pkg/example: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:22:3: undeclared name: log /Users/tschaub/projects/example/main.go:24:2: undeclared name: fmt]]"
> level=warning msg="[runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:22:3: undeclared name: log /Users/tschaub/projects/example/main.go:24:2: undeclared name: fmt]"
> level=error msg="Running error: buildir: analysis skipped: errors in package: [/Users/tschaub/projects/example/main.go:22:3: undeclared name: log /Users/tschaub/projects/example/main.go:24:2: undeclared name: fmt]"
> ```
> 
> At this point, the extension no longer works, and I see this "Your workspace is misconfigured" dialog.
> 
> ![image](https://user-images.githubusercontent.com/41094/77585894-e09b6f00-6eaa-11ea-83b5-141c4f971a89.png)

I have the same issues. When you change branch on git it happens and restarting the language server it works. I don't know if it is related with golangci

**Comment by youzeliang** [comment] 2020-04-23 10:06
golangci-lint has version 1.25.0 built from 3082512 on 2020-04-22T23:03:03Z

go version go1.14 darwin/amd64

GoLand 2020.1

and I add File Watcher using existing golangci-lint template.
 
when I save it, it seems to report "level=warning msg="[runner] Can't run linter goanalysis_metalinter: asmdecl: analysis skipped: ".....

**Comment by ernado** [comment] 2020-04-23 10:12
Hey, please provide a way to reproduce this issue.
Also don't forget to perform `golangci-lint cache clean`

**Comment by Cyantosh0** [comment] 2020-04-30 04:42
Am I also facing the same problem???

![Screenshot from 2020-04-30 10-25-56](https://user-images.githubusercontent.com/50645720/80672685-15fc3380-8acd-11ea-9de3-24204d4efa35.png)

**Comment by bacongobbler** [comment] 2020-05-14 19:16
Hey @ernado. The simplest method to reproduce the issue is to use an older version of golangci-lint (in our case, 1.21.0) and Go 1.14. The combination results in `golangci-lint run` reporting a warning on a compiler error, but succeeding instead of failing (as in, `golangci-lint run` displays warnings, but returns exit code zero).

Updating to golangci-lint 1.27.0 fixed this for us. It likely has to do with the fact that 1.21.0 was compiled with an older version of Go, and is incompatible when building packages with Go 1.14.

A [recent CI run](https://circleci.com/gh/helm/helm/12123) from helm/helm shows the same error message, which uses the [same golangci-lint](https://github.com/helm/helm/blob/b18e7e201e55ba38fdecbcf81e4da512e55444b4/.circleci/config.yml#L8) and [Go version](https://github.com/helm/helm/blob/b18e7e201e55ba38fdecbcf81e4da512e55444b4/.circleci/config.yml#L12) reported: 

```
GO111MODULE=on golangci-lint run
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/home/circleci/helm.sh/helm/cmd/helm/require/args.go:19:2: could not import github.com/pkg/errors (/go/pkg/mod/github.com/pkg/errors@v0.9.1/errors.go:96:2: could not import fmt (/usr/local/go/src/fmt/errors.go:7:8: could not import errors (/usr/local/go/src/errors/wrap.go:8:2: could not import internal/reflectlite (/usr/local/go/src/internal/reflectlite/value.go:8:2: could not import runtime (/usr/local/go/src/runtime/alg.go:8:2: could not import internal/cpu (-: could not load export data: cannot import "internal/cpu" (unknown iexport format version 1), export data is newer version - update tool)))))) /home/circleci/helm.sh/helm/cmd/helm/require/args.go:20:2: could not import github.com/spf13/cobra (/go/pkg/mod/github.com/spf13/cobra@v1.0.0/args.go:4:2: could not import fmt (/usr/local/go/src/fmt/errors.go:7:8: could not import errors (/usr/local/go/src/errors/wrap.go:8:2: could not import internal/reflectlite (/usr/local/go/src/internal/reflectlite/value.go:8:2: could not import runtime (/usr/local/go/src/runtime/alg.go:8:2: could not import internal/cpu (-: could not load export data: cannot import "internal/cpu" (unknown iexport format version 1), export data is newer version - update tool))))))] 
WARN [runner] Can't run linter goanalysis_metalinter: deadcode: analysis skipped: errors in package: [/home/circleci/helm.sh/helm/internal/version/version.go:20:2: could not import flag (/usr/local/go/src/flag/flag.go:71:2: could not import errors (/usr/local/go/src/errors/wrap.go:8:2: could not import internal/reflectlite (/usr/local/go/src/internal/reflectlite/value.go:8:2: could not import runtime (/usr/local/go/src/runtime/alg.go:8:2: could not import internal/cpu (-: could not load export data: cannot import "internal/cpu" (unknown iexport format version 1), export data is newer version - update tool))))) /home/circleci/helm.sh/helm/internal/version/version.go:21:2: could not import runtime (/usr/local/go/src/runtime/alg.go:8:2: could not import internal/cpu (-: could not load export data: cannot import "internal/cpu" (unknown iexport format version 1), export data is newer version - update tool)) /home/circleci/helm.sh/helm/internal/version/version.go:22:2: could not import strings (/usr/local/go/src/strings/builder.go:8:2: could not import unicode/utf8 (-: could not load export data: cannot import "unicode/utf8" (unknown iexport format version 1), export data is newer version - update tool))] 
```

While updating to a newer version of golangci-lint does indeed fix this issue, my main concern lies with the fact that an update to Go 1.14 caused golangci-lint to succeed in cases where compiling the project should've failed. I'm wondering if there's a case that can be captured [here](https://github.com/golangci/golangci-lint/blob/279b6d62d37265aeb8e48027de92847e089fed78/pkg/lint/runner.go#L216) that should report an error rather than [logging a warning](https://github.com/golangci/golangci-lint/blob/279b6d62d37265aeb8e48027de92847e089fed78/pkg/lint/runner.go#L217).

Hope this helps.

**Comment by ernado** [comment] 2020-05-14 20:23
Great investigation, @bacongobbler, thank you!

It is correct, older versions of golangci-lint can silently fail in such conditions :(

**Comment by ernado** [comment] 2020-05-15 15:10
I'll close this issue for now. Feel free to open another issue if this re-occurs for version after `v1.27.0`.

Thanks everybody.

**Closed by ernado** 2020-05-15 15:10 UTC
Labels: bug, cursed, feedback required
