### ISSUE TITLE
New "urlcheck" linter

### ISSUE THREAD

**Issue by 500poundbear** [golangci/golangci-lint#4148] opened 2023-10-22 05:26 UTC
### Your feature request related to a problem? Please describe.

Some URLs embedded within comments get stale and invalid over time, i.e. they stop returning HTTP 200. 

A secondary problem is that some contributors are unaware about the [Go Doc comment links](https://go.dev/doc/comment#links) recommendation to leave the actual URLs at the bottom of the comment block.

### Describe the solution you'd like.

I will like to contribute a linter that can check that:

* All urls are still returning HTTP 200
* URLs should be formatted as per Go Doc recommendation

### Describe alternatives you've considered.

-

**Comment by bombsimon** [comment] 2023-10-22 08:07
Duplicate of #4147

**Closed by bombsimon** 2023-10-22 08:07 UTC
Labels: enhancement
