### ISSUE TITLE
Generate todo list for legacy projects

### ISSUE THREAD

**Issue by MistaTwista** [golangci/golangci-lint#3650] opened 2023-03-03 11:32 UTC
### Your feature request related to a problem? Please describe.

When you adding a linter to existing project it can be hard to fix everything an once

### Describe the solution you'd like.

Add a flag to generate TODO list file with excluding rules. Something like `--auto-gen-config` in rubocop

### Describe alternatives you've considered.

Add some parser of golangci-lint output for generating excluding rules for existing params in yaml

### Additional context.

Can try to research it by myself

**Comment by ldez** [comment] 2023-03-03 12:28
duplicate of #2600

**Closed by ldez** 2023-03-03 12:28 UTC
Labels: enhancement
