### ISSUE TITLE
Running error: context loading failed: package github.com/golangci/golangci-lint/pkg/commands: no go files to analyze

### ISSUE THREAD

**Issue by Anjana-Prabhakar** [golangci/golangci-lint#916] opened 2020-01-10 10:02 UTC
Thank you for creating the issue!

- [x] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

Please include the following information:

<details><summary>Version of golangci-lint</summary>
```console
$ golangci-lint --version
golangci-lint has version (devel) built from (unknown, mod sum: "") on (unknown)
```

</details>

<details><summary>Config file</summary>

```console
$ cat .golangci.yml
linters:
  disable-all: true
  enable:
    - unused
linters-settings:
  unused:
    check-exported: true
```

</details>

<details><summary>Go environment</summary>

```console
$ go version && go env
# paste output here
```

</details>

<details><summary>Verbose output of running</summary>

```console
$ golangci-lint run -v
# paste output here
```

</details>
i get an error "Running error: context loading failed: package github.com/golangci/golangci-lint/pkg/commands: no go files to analyze" even when there are go files in the location.

**Comment by Dominik-K** [comment] 2020-01-13 17:39
@Anjana-Prabhakar: What's the output when adding the environment variables `GL_DEBUG=linters_output GOPACKAGESPRINTGOLISTERRORS=1`?

**Comment by Anjana-Prabhakar** [comment] 2020-01-16 08:12
@Dominik-K Thanks for the response. I added the variables to .bashrc. The error remains the same though.

**Comment by Dominik-K** [comment] 2020-01-16 11:08
@Anjana-Prabhakar There should be more output now. Can you paste it here, please?

**Comment by Anjana-Prabhakar** [comment] 2020-01-17 04:56
@Dominik-K I am sorry but its still the same one line error that i get. 
Is it sufficient that I add the lines 
```
export GL_DEBUG=linters_output 
export GOPACKAGESPRINTGOLISTERRORS=1
```
to ~/.bashrc , followed by the command 
`source ~/.bashrc`

**Comment by Dominik-K** [comment] 2020-01-27 13:12
@Anjana-Prabhakar Yes, that should be sufficient. You can also add these environments before the `golangci-lint` command.

**Comment by fdcds** [comment] 2020-02-13 18:24
Probably a duplicate of #825.

**Comment by jirfag** [comment] 2020-05-18 07:53
Duplicate of #825

**Closed by jirfag** 2020-05-18 07:53 UTC
Labels: bug
