### ISSUE TITLE
level=error msg="Running error: context loading failed: package github.com/sirupsen/logrus: no go files to analyze"

### ISSUE THREAD

**Issue by rafaelvanoni** [golangci/golangci-lint#870] opened 2019-11-27 21:09 UTC
I'm hitting this error when running golangci-lint v1.20.0 on github.com/projectcalico/libcalico-go

`level=error msg="Running error: context loading failed: package github.com/sirupsen/logrus: no go files to analyze"`

> $ go env
> GO111MODULE="on"
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/go-cache"
> GOENV="/home/user/.config/go/env"
> GOEXE=""
> GOFLAGS="-mod=vendor"
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/usr/local/go"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> AR="ar"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="0"
> GOMOD="/go/src/github.com/projectcalico/libcalico-go/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build253984656=/tmp/go-build -gno-record-gcc-switches"

The go.mod in libcalico-go replaces logrus with our fork of that package, but the problem persists if I remove that replace statement.

**Comment by rafaelvanoni** [comment] 2019-12-02 18:58
Running `go mod vendor` before golangci-lint fixed this issue. But I'm not sure if golangci-lint should have considered `GOFLAGS="-mod=vendor"`, so I'll leave this open for further comments.

**Comment by fdcds** [comment] 2020-02-13 18:24
Probably a duplicate of #825.

**Comment by jirfag** [comment] 2020-05-18 07:52
Duplicate of #825

**Closed by jirfag** 2020-05-18 07:52 UTC
Labels: bug
