### ISSUE TITLE
Support macOS Catalina for golangci-lint-1.28.3-darwin-amd64

### ISSUE THREAD

**Issue by doug4j** [golangci/golangci-lint#1251] opened 2020-07-18 13:55 UTC
**Is your feature request related to a problem? Please describe.**
The entire workflow of golangci-lint including use in Visual Studio Code does not work on macOS Catalina, getting dialog from the OS: 
```"golangci-lint" cannot be opened because the developer cannot be verified.```
![Screen Shot of Error Message](https://user-images.githubusercontent.com/1514133/87853689-2658c900-c8da-11ea-954a-119d1c50b1dd.jpg)

**Describe the solution you'd like**
The optimal solution is for the binary packaged with golangci-lint-1.28.3-darwin-amd64 distribution to be signed with macOS Notarization. I recommend the use of https://github.com/mitchellh/gon as it integrates with goreleaser,  see https://github.com/goreleaser/goreleaser/issues/1227. This will allow golangci-lint to operate alongside other developer workflows without friction.
Note: goreleaser itself is macOS Notarized.

**Describe alternatives you've considered**
Theoretically, one can turn off macOS Notarization systemwide... but, this is antithetical to default macOS security practices and creates.

**Additional context**
- none -

**Comment by doug4j** [comment] 2020-07-18 14:01
I'm open to contributing a patch for this... but this is a *build-time improvement* and the solution *requires an apple developer account*. I have solved this for my personal projects and have automation going with goreleaser. I'm familiar with these go+macOS notarization workflows. For official distribution, I'm sure *the golangci project will want this to be signed by your organization's appleid* and not one of my developer accounts. I can setup the contributor workflow as a first step as instructed here:  https://golangci-lint.run/contributing/workflow/

**Comment by SVilgelm** [comment] 2020-07-18 19:01
I think we need to ask @jirfag first. 
at second it's not free, so someone should pay for this. It will be better if @jirfag will take care of it. Maybe we can sponsor, the price is not so huge.
and there is a third - is there anything that stops you from using homebrew? It work well, no issues with certificates and etc...

**Comment by doug4j** [comment] 2020-07-18 21:45
Wonderful @SVilgelm . That worked beautifully. Thank you. 🙌

I didn't realize there was a difference in the build pipeline from what is posted in the github tags for the project and what made its way to homebrew. Previously, I had used the distribution from Github as I tend to do for most projects. I rarely use homebrew, preferring to have greater traceability over software running on my machine via github... though homebrew is certainly convenient. In the case of `golangci-lint --version` you conveniently print the the hash of the release in addition to the build number. So that's awesome. 

Clearly, somewhere along the build pipeline for homebrew conveniently provides macOS notarization. Nice!

**The only disadvantage I can see in using homebrew is that the builds are behind the latest github releases**. I don't know the standard lag time. I see that the latest in homebrew is this version:

```
golangci-lint --version 
golangci-lint has version 1.27.0 built from fb74c2e on 2020-05-13T18:45:55Z
```

At the time of this writing, 1.28.3 is out... which is **a lag time of ~60 days** from the 1.27.0 build. The lag time isn't awful. But, it's not like waiting a day or two—which would be preferred if there is a new feature or bug fix to leverage.

In this case, I'm good. So thank you. I'm happy to close this ticket. @jirfag , if you're interested in improving the pipeline natively to the https://github.com/golangci/golangci-lint/releases for macOS, **I'd be happy to share my experience on other projects** using https://github.com/mitchellh/gon and integrating goreleaser (see goreleaser/goreleaser#1227).

Thanks much golangci-lint team. Your project is the best go linter I've experienced. It's helped me improve the quality of my code and related developer workflows. It's great that I can do this having upgraded to macOS Catalina too!

**Comment by SVilgelm** [comment] 2020-07-19 02:44
I really glad that it works. About the delay - it is caused by the wrong permissions CI token had, but @jirfag fixed that problem. We are going to release the `v1.29.0` soon. Here is the discussion: https://github.com/orgs/golangci/teams/team/discussions/3
Then we should not have any delays.

**Comment by julienschmidt** [comment] 2020-07-19 16:58
@SVilgelm Just an aside: These team discussions are only visible to the team members

**Comment by SVilgelm** [comment] 2020-07-19 18:54
@julienschmidt Oh yeah, thank you.

**Comment by SVilgelm** [comment] 2020-07-21 01:13
@doug4j We have updated the homebred-tap repo with `v1.29.0`, so we do not expect any delays anymore. The release workflow should update it at same time with release other binaries.

**Comment by bombsimon** [comment] 2020-10-12 06:05
I'll close this for now, let's re-open if we want to pick up the signing.

**Closed by bombsimon** 2020-10-12 06:05 UTC
Labels: enhancement
