### ISSUE TITLE
Homebrew is outdated

### ISSUE THREAD

**Issue by kamilsk** [golangci/golangci-lint#1237] opened 2020-07-12 06:10 UTC
Hi! The binary provided by brew still has the v1.27.0 version because builds have the error.

> release failed after 515.64s error=homebrew tap formula: failed to publish artifacts: PUT https://api.github.com/repos/golangci/homebrew-tap/contents/Formula/golangci-lint.rb: 404 Not Found []

- https://github.com/golangci/golangci-lint/runs/856068778?check_suite_focus=true
- https://github.com/golangci/golangci-lint/runs/861667933?check_suite_focus=true

**Comment by SVilgelm** [comment] 2020-07-12 16:26
Yeah, it's know issue and we need a help from @golangci/core-team to check the permissions of the GitHub token used for the release action.
I'm closing it as a duplicate of the https://github.com/golangci/homebrew-tap/issues/8

**Closed by SVilgelm** 2020-07-12 16:26 UTC
Labels: bug

**Comment by nigurr** [comment] 2020-07-14 16:08
@golangci-releaser please fix homebrew.
