### ISSUE TITLE
Multiple Issues don't seem to play nice together.

### ISSUE THREAD

**Issue by thebeline** [golangci/golangci-lint#1874] opened 2021-03-26 20:15 UTC
I have one file where the `push` makes one line super long, and adds weird whitespace somewhere else.

I get a `gofumpt` error on the whitespace (first), and then on the **long line** (what I am referring to from here forward) I get another `gofumpt` error.

If I disable `gofumpt`, it (super weird) turns into a `goimports` error (but still on that long line), even though I have enabled `only-new-issues: true` and didn't touch the `import` section at all.

Then... If I turn on `--fix` (which the Action can't do), with `gofumpt` back on, I get a slew of `info` things (in the log) and an `lll` error, finally...

I mean...  A few issues here:

- I don't understand how or why `goimports` is triggering when I didn't touch the imports.  Except for maybe it was using something that was imported, but since `only-new-issues: true` is designed to keep the issues related to what the Push or PR actually changes, it seems weird.
- If the system can annotate, it would be SWELL if it could group the annotations in some way, so you aren't patching and pushing just to chase ghosts.  Having all of the detected issues right there would be ideal.
- The descriptions (`File is not `gofumpt`-ed with `-extra` (gofumpt)`) REALLY could use some translation.  I feel like there is enough data there to determine what the issue is in human readable terms.

**Comment by ldez** [comment] 2021-03-27 15:00
Duplicate of #1490

**Closed by ldez** 2021-03-27 15:00 UTC
Labels: duplicate

**Comment by ldez** [comment] 2021-03-27 17:21
https://github.com/golangci/golangci-lint/discussions/1875

**Comment by thebeline** [comment] 2021-03-28 17:57
I am not entirely sure what was going on here, but it seems resolved.
