### ISSUE TITLE
Integrate new deadcode tool

### ISSUE THREAD

**Issue by quite** [golangci/golangci-lint#4270] opened 2023-12-19 08:31 UTC
### Your feature request related to a problem? Please describe.

The new deadcode from the official Go tools seems very useful for finding unused functions. See https://go.dev/blog/deadcode

### Describe the solution you'd like.

Integration of running deadcode as part of golangci-lint

### Describe alternatives you've considered.

None.

**Comment by ldez** [comment] 2023-12-19 12:23
Duplicate of #4254

**Closed by ldez** 2023-12-19 12:23 UTC
Labels: duplicate
