### ISSUE TITLE
Too much memory consumption, especially linter using ssa package. Memory: 811 samples, avg is 10074.1MB, max is 30712.9MB

### ISSUE THREAD

**Issue by sichen-qin** [golangci/golangci-lint#634] opened 2019-08-09 08:59 UTC
## 1. 1. Version of golangci-lint: `golangci-lint --version` (or git commit if you don't use binary distribution)
```
golangci-lint has version 1.17.1 built from 4ba2155 on 2019-06-10T09:06:49Z
```

## 2. Config file: `cat .golangci.yml`
I did not use config file, just execute the following command：  
```
golangci-lint run -v --out-format=checkstyle --no-config --deadline=30m -E=gosec -E=prealloc -E=golint -E=goconst -E=misspell -D=typecheck --skip-dirs=vendor --skip-dirs=.gogradle --skip-files=\"configgenerater.go\" --skip-files=\"cm_go.*.go\" --skip-files=\"exec.go\" --skip-files=\"builder.go\" --skip-files=\"ctrl.go\" --skip-files=\".ddf.go\" --skip-files=\".auto.go\" --skip-files=\"infocode.go\" --skip-files=\".pb.go\" --skip-files=\"cgen.*\" --skip-files=\"korat.*\" --skip-files=\"cm_datatype_extension.go\" --skip-dirs=\"alpha\" --skip-dirs=\"omcmtbl\" --skip-dirs=\"temptbl\" --skip-dirs=\"logctrl\" --skip-dirs=\"logexec\" --skip-dirs=\"cm_go\" ./.gogradle/project_gopath/src/5gcore/cp/domain/user/... > .gogradle/reports/golangci_chk.xml
```
## 3. Go environment: `go version && go env`
```
go version && go env
go version go1.12.4 linux/amd64
GOARCH="amd64"
GOBIN=""
GOCACHE="/usr1/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/golang"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go1.12.4"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go1.12.4/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build826187120=/tmp/go-build -gno-record-gcc-switches"
```
## 4. Verbose output of running: `golangci-lint run -v`
```
INFO [lintersdb] Active 14 linters: [deadcode errcheck goconst golint gosec gosimple govet ineffassign misspell prealloc staticcheck structcheck unused varcheck]
INFO [lintersdb] Optimized sublinters [staticcheck gosimple unused] into metalinter megacheck
INFO [loader] Go packages loading at mode load types and syntax took 45.119440508s
INFO [loader] SSA repr building timing: packages building 188.073999ms, total 6.468977713s
INFO [runner] worker.1 took 19.147µs
INFO [runner] worker.3 took 2.636µs
INFO [runner] worker.8 took 902ns
INFO [runner] worker.2 took 16.133µs
INFO [runner] worker.13 took 184.677419ms with stages: errcheck: 184.65048ms
INFO [runner] worker.12 took 1.706719559s with stages: prealloc: 1.706682173s
INFO [runner] worker.4 took 7.766686879s with stages: goconst: 7.766660955s
INFO [runner] worker.5 took 9.054900539s with stages: deadcode: 9.054875539s
INFO [runner] worker.7 took 9.637278726s with stages: structcheck: 9.637262478s
INFO [runner] worker.10 took 11.678322748s with stages: varcheck: 11.678283078s
INFO [runner] worker.16 took 13.38883285s with stages: misspell: 13.388807618s
INFO [runner] worker.6 took 15.158949804s with stages: ineffassign: 15.158904113s
INFO [runner] worker.14 took 15.399470945s with stages: govet: 15.399426719s
WARN [runner] Can't process result by autogenerated_exclude processor: can't filter issue result.Issue{FromLinter:"govet", Text:"nilness: nil dereference in field selection", Pos:token.Position{Filename:"", Offset:0, Line:0, Column:0}, LineRange:(*result.Range)(nil), HunkPos:0, SourceLines:[]string(nil), Replacement:(*result.Replacement)(nil)}: no file path for issue
WARN [runner] Can't process result by nolint processor: can't filter issue result.Issue{FromLinter:"govet", Text:"nilness: nil dereference in field selection", Pos:token.Position{Filename:"", Offset:0, Line:0, Column:0}, LineRange:(*result.Range)(nil), HunkPos:0, SourceLines:[]string(nil), Replacement:(*result.Replacement)(nil)}: no file path for issue
WARN [runner/source_code] Failed to get line 0 for file : failed to get file  lines cache: can't get file  bytes from cache: can't read file : open : no such file or directory
INFO [runner] worker.11 took 17.791996536s with stages: gosec: 17.791956882s
INFO [runner] worker.9 took 25.075687221s with stages: golint: 25.075601435s
INFO [runner] worker.15 took 43.091902324s with stages: megacheck: 43.091871055s
INFO [runner] Workers idle times: #1: 43.087507992s, #2: 43.08722518s, #3: 43.087426952s, #4: 35.324604725s, #5: 34.032915206s, #6: 27.932307607s, #7: 33.450472876s, #8: 43.087340804s, #9: 18.016200369s, #10: 31.409450246s, #11: 25.299334907s, #12: 41.384196821s, #13: 42.902924139s, #14: 27.692428958s, #16: 29.703005712s
INFO [runner/skip dirs] Skipped dir secm/exec/alpha/datadefine/nedata by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/scantask/alpha by pattern alpha
INFO [runner/skip dirs] Skipped dir ngecm/exec/do/alpha/datadefine by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tngecm by pattern alpha
INFO [runner/skip dirs] Skipped dir ngecm/exec/temptbl by pattern temptbl
INFO [runner/skip dirs] Skipped dir internal/alpha/msgwrapper/toutmsg by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/stabledata by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/interworking by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/ueconfigurationupdate by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/handover by pattern alpha
INFO [runner/skip dirs] Skipped dir ngecm/exec/do/alpha/testobject by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/service_request by pattern alpha
INFO [runner/skip dirs] Skipped dir ngecm/exec/ds/alpha/datadefine by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/tnfdata by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tmme by pattern alpha
INFO [runner/skip dirs] Skipped dir secm/exec/alpha/testobject by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/deregistration by pattern alpha
INFO [runner/skip dirs] Skipped dir uem/exec/alpha/templateid by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/tiedata by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tomcm by pattern alpha
INFO [runner/skip dirs] Skipped dir ngecm/exec/alpha by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tsmf29502 by pattern alpha
INFO [runner/skip dirs] Skipped dir uem/exec/alpha/drivemsg by pattern alpha
INFO [runner/skip dirs] Skipped dir ngecm/ctrl/alpha by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/commfunc by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tamf29518 by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tnssf29531 by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/testobject by pattern alpha
INFO [runner/skip dirs] Skipped dir uem/exec/alpha/actionmsg by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tudm29503 by pattern alpha
INFO [runner/skip dirs] Skipped dir ngecm/exec/alpha/commfunc by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/backupmsg by pattern alpha
INFO [runner/skip dirs] Skipped dir locm/exec/alpha/presetdata by pattern alpha
INFO [runner/skip dirs] Skipped dir ngecm/exec/alpha/templateid by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/ttopo by pattern alpha
INFO [runner/skip dirs] Skipped dir secm/exec/alpha/datadefine by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/subdatachange by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tsecm by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tueam by pattern alpha
INFO [runner/skip dirs] Skipped dir secm/exec/alpha/commfunc by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/drivemsg by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tgtp29274 by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/templateid by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tnas24501 by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgwrapper/tinmsg by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tausf29509 by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tngap by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tuem by pattern alpha
INFO [runner/skip dirs] Skipped dir ngecm/exec/ds/alpha/testobject by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/registration by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/eventexposure by pattern alpha
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/pdulevelproc by pattern alpha
INFO [runner/skip dirs] Skipped dir locm/exec/alpha/actionmsg by pattern alpha
INFO [runner/skip dirs] Skipped dir uem/exec/alpha/commfunc by pattern alpha
INFO [runner/skip dirs] Skipped dir uem/exec/alpha/testobject by pattern alpha
INFO [runner/skip dirs] Skipped dir locm/exec/alpha/commfunc by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tlocm by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/alpha/msgtemplate/tpolicy by pattern alpha
INFO [runner/skip dirs] Skipped dir ngecm/exec/omcmtbl by pattern omcmtbl
INFO [runner/skip dirs] Skipped dir ueam/exec/alpha/actionmsg/anrelease by pattern alpha
INFO [runner/skip dirs] Skipped dir internal/userperf/alpha by pattern alpha
INFO [runner/max_same_issues] 184/187 issues with text "method GetEventId should be GetEventID" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 122/125 issues with text "composites: `5gcore/cp/domain/user/vendor/5gcore/cp/lib/alpha/testbase.IETypeValuePair` composite literal uses unkeyed fields" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 77/80 issues with text "method GetTransId should be GetTransID" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 60/63 issues with text "S1023: redundant `return` statement" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 44/47 issues with text "method parameter `pduSessionId` should be `pduSessionID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 38/41 issues with text "interface method parameter `pduSessionId` should be `pduSessionID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 35/38 issues with text "var `pduSessionId` should be `pduSessionID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 26/29 issues with text "S1008: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>'" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 17/20 issues with text "S1001: should use copy() instead of a loop" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 17/20 issues with text "range var `pduSessionId` should be `pduSessionID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 16/19 issues with text "var `ueId` should be `ueID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 9/12 issues with text "var `ranId` should be `ranID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 9/12 issues with text "S1019: should use make([]byte, length) instead" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 8/11 issues with text "var `pduId` should be `pduID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 7/10 issues with text "method BuildHttpHeader should be BuildHTTPHeader" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 6/9 issues with text "receiver name ia should be consistent with previous receiver name i for InitBackUpRegistrationEvent" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 6/9 issues with text "var `subscriptionId` should be `subscriptionID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 6/9 issues with text "receiver name ia should be consistent with previous receiver name i for InitIntraRegistrationEvent" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 6/9 issues with text "SA9003: empty branch" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 6/9 issues with text "method BuildHttpIndicator should be BuildHTTPIndicator" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 5/8 issues with text "receiver name mr should be consistent with previous receiver name i for BackUpPeriodicRegistrationEvent" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 5/8 issues with text "var `n2ContextId` should be `n2ContextID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 5/8 issues with text "method parameter `ueId` should be `ueID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 5/8 issues with text "S1019: should use make([]byte, len(k)) instead" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 5/8 issues with text "range var `pduId` should be `pduID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 5/8 issues with text "SA9004: only the first constant in this group has an explicit type" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 5/8 issues with text "receiver name mr should be consistent with previous receiver name i for PeriodicRegistrationEvent" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 4/7 issues with text "var `n1ContextId` should be `n1ContextID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 4/7 issues with text "struct field `ueId` should be `ueID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "S1021: should merge variable declaration with assignment on next line" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "method HttpHeader should be HTTPHeader" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "func parameter `transId` should be `transID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "var `plmnId` should be `plmnID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "method GetHttpHead should be GetHTTPHead" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "method parameter `pduId` should be `pduID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "S1019: should use make([]byte, 4) instead" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "struct field `HttpHeader` should be `HTTPHeader`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 3/6 issues with text "ineffectual assignment to `err`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "var `subId` should be `subID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "method ConflictWaitingEventId should be ConflictWaitingEventID" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "func parameter `ngapRanId` should be `ngapRanID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "nilness: nil dereference in field selection" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "var `ranNodeId` should be `ranNodeID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "method WithWaitingEventId should be WithWaitingEventID" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "struct field `SessionId` should be `SessionID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "S1019: should use make([]transdsl.EventId, len(eventIds)) instead" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "method parameter `conflictTransId` should be `conflictTransID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "func WriteJsonMsg should be WriteJSONMsg" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "method parameter `msgId` should be `msgID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "method parameter `subscriptionId` should be `subscriptionID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "var `peerIp` should be `peerIP`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 2/5 issues with text "var `localIpType` should be `localIPType`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "interface method parameter `pduId` should be `pduID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "struct field `PduSessionId` should be `PduSessionID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "method parameter `plmnId` should be `plmnID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "var `localIp` should be `localIP`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "method buildHttpLocation should be buildHTTPLocation" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "var `ngEnbId` should be `ngEnbID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "struct field `msgId` should be `msgID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "interface method parameter `ueId` should be `ueID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "method HttpIndicator should be HTTPIndicator" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "method parameter `timerId` should be `timerID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "method parameter `anId` should be `anID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "S1019: should use make([]uint8, aesBlockSize) instead" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "receiver name m should be consistent with previous receiver name s for UemCancelCmdSteadyEvent" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "S1019: should use make([]byte, N2Transfer.Len) instead" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "Consider preallocating `result`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "method CurTransId should be CurTransID" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "func parameter `timerId` should be `timerID`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "method fillAmfUeNgapId should be fillAmfUeNgapID" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "composites: `5gcore/cp/domain/user/vendor/5gcore/cp/lib/itf/cs/sctp/sctpconn.AddrInfo` composite literal uses unkeyed fields" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "var `callbackUri` should be `callbackURI`" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "S1009: should omit nil check; len() for nil slices is defined as zero" were hidden, use --max-same-issues
INFO [runner/max_same_issues] 1/4 issues with text "func parameter `ranId` should be `ranID`" were hidden, use --max-same-issues
INFO [runner/max_from_linter] 1116/1166 issues from linter golint were hidden, use --max-issues-per-linter
INFO [runner/max_from_linter] 280/330 issues from linter gosimple were hidden, use --max-issues-per-linter
INFO [runner/max_from_linter] 34/84 issues from linter structcheck were hidden, use --max-issues-per-linter
INFO [runner] Issues before processing: 28328, after processing: 294
INFO [runner] processing took 2.387052221s with stages: skip_files: 822.528099ms, skip_dirs: 503.950405ms, identifier_marker: 251.909639ms, autogenerated_exclude: 238.857753ms, exclude: 226.262053ms, path_prettifier: 193.053178ms, cgo: 70.317164ms, filename_unadjuster: 45.016641ms, nolint: 17.0357ms, source_code: 9.642277ms, max_same_issues: 4.464593ms, uniq_by_line: 2.133007ms, max_from_linter: 937.501µs, max_per_file_from_linter: 703.948µs, path_shortener: 226.034µs, diff: 9.314µs, exclude-rules: 4.915µs
INFO File cache stats: 2859 entries of total size 14.2MiB
INFO Memory: 811 samples, avg is 10074.1MB, max is 30712.9MB
INFO Execution took 1m37.15299992s
```

**Comment by jirfag** [comment] 2019-09-23 19:02
Hi!
I've significantly reduced memory usage of staticcheck, gosimple, stylechekc, govet and bodyclose.
Please, try the latest version from the master branch.

**Comment by tpounds** [comment] 2019-09-25 15:49
Closing as duplicate of https://github.com/golangci/golangci-lint/issues/337.

**Closed by tpounds** 2019-09-25 15:49 UTC
Labels: duplicate, memory
