### ISSUE TITLE
staticcheck results missing

### ISSUE THREAD

**Issue by pckilgore** [golangci/golangci-lint#3495] opened 2023-01-20 17:50 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Missing results from `staticcheck` that exist with same configuration for standalone.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.50.1 built from 8926a95 on 2022-10-22T10:48:48Z
```

</details>

### Configuration file

<details>

```yml
issues:
  exclude-use-default: false

linters-settings:
  staticcheck:
    checks:
      - all

linters:
  disable-all: true
  enable:
    - staticcheck

```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.19.5 darwin/arm64
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/<snip>/Library/Caches/go-build"
GOENV="/Users/<snip>/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/<snip>/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/<snip>/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.19.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.5/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.5"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/<snip>/<snip>/<snip>/src/golang/src/<snip>/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wr/kbfw8_254yd97jvcn83k71m80000gn/T/go-build4172845769=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run . -v
INFO [config_reader] Config search paths: [<SNIPPED>]
INFO [config_reader] Used config file .golangci.yml
INFO [lintersdb] Active 1 linters: [staticcheck]
INFO [loader] Go packages loading at mode 575 (compiled_files|deps|exports_file|name|files|imports|types_sizes) took 116.459709ms
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 749.459µs
INFO [linters_context/goanalysis] analyzers took 8.915093ms with top 10 stages: buildir: 2.172416ms, SA4031: 522.625µs, nilness: 449.204µs, SA5012: 444.169µs, typedness: 370.129µs, fact_purity: 340.42µs, fact_deprecated: 297.753µs, SA1016: 276.583µs, SA1004: 275.5µs, SA5004: 252.875µs
INFO [runner] processing took 2.125µs with stages: max_same_issues: 459ns, nolint: 291ns, max_from_linter: 250ns, skip_dirs: 250ns, cgo: 166ns, source_code: 125ns, path_prettifier: 83ns, filename_unadjuster: 42ns, sort_results: 42ns, diff: 42ns, severity-rules: 42ns, exclude-rules: 42ns, path_prefixer: 42ns, max_per_file_from_linter: 42ns, skip_files: 42ns, identifier_marker: 42ns, exclude: 41ns, uniq_by_line: 41ns, autogenerated_exclude: 41ns, path_shortener: 0s
INFO [runner] linters took 25.727125ms with stages: staticcheck: 25.6915ms
INFO File cache stats: 0 entries of total size 0B
INFO Memory: 3 samples, avg is 31.3MB, max is 37.4MB
INFO Execution took 149.432959ms
```

</details>

### Code example or link to a public repository

<details>

```console
$ la
.golangci.yml  main.go
```

the yml is as above.

`cat main.go` is below:

```go
package main

import "fmt"

// ThisIsWrong is a stupid struct.
type MyExportedType struct{}

func main() {
	it := MyExportedType{}
	fmt.Printf("%v", it)
}
```

The staticcheck linter says:

```console
$ staticcheck -checks=all
main.go:5:1: comment on exported type MyExportedType should be of the form "MyExportedType ..." (with optional leading article) (ST1021)
```

That's expected.

The golangci-lint linter result is as above, with no lint errors printed.

</details>

**Comment by ldez** [comment] 2023-01-21 13:21
Hello,

`staticcheck` is a binary **and** a set of rules, those rules are grouped into "category": `staticcheck`, `gosimple`, `stylecheck` and `unused`.

- [staticcheck](https://github.com/dominikh/go-tools/blob/331bcca40621580531c9b8a9cb7d5c2c06c709d2/staticcheck/analysis.go#L23)
- [stylecheck](https://github.com/dominikh/go-tools/blob/331bcca40621580531c9b8a9cb7d5c2c06c709d2/stylecheck/analysis.go#L14)
- [simple](https://github.com/dominikh/go-tools/blob/331bcca40621580531c9b8a9cb7d5c2c06c709d2/simple/analysis.go#L11)
- [unused](https://github.com/dominikh/go-tools/blob/331bcca40621580531c9b8a9cb7d5c2c06c709d2/unused/unused.go#L418)

Inside golangci-lint we use the sets of rules, not the binary.

The rule `ST1021` is related to the `stylecheck` set:
- `STxxx` -> `stylecheck`
- `SAxxx` -> `staticcheck`

Duplicate of #3455

**Closed by ldez** 2023-01-21 13:21 UTC
Labels: duplicate, question

**Comment by pckilgore** [comment] 2023-01-21 18:32
I see.  So `staticcheck : rule category :: golang-ci : linter`

Thanks for the clarification & the project! A great example of why a lot of linters consider shadowing a name to be an antipattern 😆.

**Comment by pckilgore** [comment] 2023-01-21 18:36
Future readers in view of https://xkcd.com/979/

This works as expected (see my earlier yml):
```
issues:
  exclude-use-default: false

linters-settings:
  # Optionally here: [gosimple, unused] per above Idez
  stylecheck:
    checks:
      - all
  staticcheck:
    checks:
      - all

linters:
  disable-all: true
  enable:
      # Optionally here: [gosimple, unused] per above Idez
    - staticcheck
    - stylecheck
```
