### ISSUE TITLE
golangci-lint is using go v1.19 for gofmt linter inspite of using go v1.17 in the github action

### ISSUE THREAD

**Issue by nishantwrp** [golangci/golangci-lint#3077] opened 2022-08-07 10:56 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

In our golangci-lint github [workflow](https://github.com/meshery/meshery/blob/master/.github/workflows/mesheryctl-ci.yml#L21-L37), we use go `v1.17.x`. The errors pointed out by the `gofmt` linter (see [here](https://github.com/meshery/meshery/pull/5988/files)) doesn't seem to get fixed when using `gofmt -s .` with the binary provided by `go v.17.13` but they do get fixed with running the binary provided by `go v1.19`. 

Here is our [.golangci.yml](https://github.com/meshery/meshery/blob/master/.golangci.yml) config. How should I modify the config for it to use the `go fmt` linter corresponding to the go version that I'm using in the CI?

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# paste output here
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# paste output here
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
# paste output here
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by ldez** [comment] 2022-08-07 11:48
duplicate of #3069 and https://github.com/golangci/golangci-lint-action/issues/535

**Closed by ldez** 2022-08-07 11:48 UTC
Labels: bug

**Comment by ldez** [comment] 2022-08-07 11:54
Offtopic

golangci-lint team as Go team supports only the 2 latest minor versions of Go.

https://golangci-lint.run/usage/faq/#which-go-versions-are-supported

Go v1.17 will not receive any security patch so it's recommended to update to at least go1.18.

**Comment by nishantwrp** [comment] 2022-08-07 11:59
Yup, but even `gofmt` that comes with `go v1.18` doesn't fix the errors pointed out.

**Comment by ldez** [comment] 2022-08-07 12:03
My remark is explicitly offtopic, so yes this will not change your problem...
