### ISSUE TITLE
gci+goimports = duplicated imports

### ISSUE THREAD

**Issue by howardjohn** [golangci/golangci-lint#1490] opened 2020-11-03 01:32 UTC
Config:
```yaml
linters:
  disable-all: true
  enable:
  - goimports
  - gci
  fast: false

linters-settings:
  goimports:
    local-prefixes: istio.io/
```

Input:
```go
package main

import (
	"fmt"
	"istio.io/istio/pkg/test/framework/resource"
	"os"

	"istio.io/istio/pkg/test/framework/resource"
)

var (
	_ = resource.Cluster
	_ = fmt.Println
	_ = os.Stdout
)
```

Output:
```go
package main

import (
	"fmt"
	"os"

	"istio.io/istio/pkg/test/framework/resource"
	"istio.io/istio/pkg/test/framework/resource"

	"istio.io/istio/pkg/test/framework/resource"
)

var (
	_ = resource.Cluster
	_ = fmt.Println
	_ = os.Stdout
)
```

Output seems nondeterministic

cc @daixiang0

**Comment by howardjohn** [comment] 2020-11-03 01:35
Input:

```go
import (
	"fmt"
	"os"

	"istio.io/istio/pkg/test/framework/resource"
	"istio.io/istio/pkg/test/framework/resource"
	"istio.io/istio/pkg/test/framework/components/prometheus"
)
```

Output:
```
import (
	"fmt"
	"os"

	"istio.io/istio/pkg/test/framework/components/prometheus"
)
```

**Comment by howardjohn** [comment] 2020-11-03 01:36
Also can only reproduce through golangci-lint, not direct calls on `goimports -local istio.io -w main.go; gci -local istio.io -w main.go`

**Comment by ldez** [comment] 2021-02-14 14:06
I try with different cases:

```go
import (
	"io/ioutil"
	"github.com/golangci/sandbox/pkg/render"
	"github.com/ghodss/yaml"
	"log"
	"encoding/json"

	"github.com/golangci/sandbox/pkg/router"
)
```

```go
import (
	"github.com/golangci/sandbox/pkg/render"
	"github.com/golangci/sandbox/pkg/router"
	"encoding/json"
	"io/ioutil"
	"log"
	"github.com/ghodss/yaml"
)
```

and all the linters that handle the imports (`gofmt`, `goimports`, `gci`, `gofumpt`).

Results:

| linters                           | results |
|-----------------------------------|---------|
| gofmt + goimports                 | FAIL    |
| gofmt + gci                       | FAIL    |
| goimports + gci                   | FAIL    |
| goimports + gofumpt               | FAIL    |
| gofmt + gci + gofumpt             | FAIL    |
| gofmt + goimports + gci + gofumpt | FAIL    |
| gci + gofumpt                     | OK      |
| gofmt + gofumpt                   | OK      |


I think that the problem is not related to a specific linter but to how the fixes are applied.

**Comment by dbraley** [comment] 2021-03-09 14:34
I'm also seeing this problem. I'll add that with a larger set of imports and more randomization, I'm able to reproduce the failure with the `gci + gofumpt` and `gofmt + gofumpt` combinations as well.

**Comment by danielhochman** [comment] 2021-03-09 17:30
I've started debugging this issue. I'll try to post more as I have time to dig into the results.

**Input**
```golang
import (
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"context"
	"errors"
	"fmt"

	"github.com/uber-go/tally"
	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	auditv1 "github.com/lyft/clutch/backend/api/audit/v1"
	"github.com/lyft/clutch/backend/gateway/log"
	"github.com/lyft/clutch/backend/gateway/meta"
	"github.com/lyft/clutch/backend/middleware"
	"github.com/lyft/clutch/backend/service"
	auditservice "github.com/lyft/clutch/backend/service/audit"
	"github.com/lyft/clutch/backend/service/authn"
)
```

**Expected Output**
```golang
import (
	"context"
	"errors"
	"fmt"

	"github.com/uber-go/tally"
	"go.uber.org/zap"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/anypb"

	auditv1 "github.com/lyft/clutch/backend/api/audit/v1"
	"github.com/lyft/clutch/backend/gateway/log"
	"github.com/lyft/clutch/backend/gateway/meta"
	"github.com/lyft/clutch/backend/middleware"
	"github.com/lyft/clutch/backend/service"
	auditservice "github.com/lyft/clutch/backend/service/audit"
	"github.com/lyft/clutch/backend/service/authn"
)
```

**Actual Output**
<img src="https://user-images.githubusercontent.com/4712430/110511627-03c62b00-80ca-11eb-8cca-ea2800a9368c.png" width="400px" />

**Debug Output**
I added a some extra log statements in a custom build to figure out what's happening internally, so you can see what the linter returns, how golangci-lint parses the diff, and how it merges the diffs.
```
$ golangci-lint run --fix
DEBU [importissue] goimports diff:
--- github.com/lyft/clutch/backend/middleware/audit/audit.go.orig 2021-03-09 10:57:17.396813013 -0600
+++ github.com/lyft/clutch/backend/middleware/audit/audit.go      2021-03-09 10:57:17.396813013 -0600
@@ -5,12 +5,13 @@
 // <!-- END clutchdoc -->
 
 import (
-       "google.golang.org/grpc/codes"
-       "google.golang.org/grpc/status"
        "context"
        "errors"
        "fmt"
 
+       "google.golang.org/grpc/codes"
+       "google.golang.org/grpc/status"
+
        "github.com/uber-go/tally"
        "go.uber.org/zap"
        "google.golang.org/grpc" 
        
DEBU [importissue] goimports: pos 8     range 8-9
replacement:
- NeedOnlyDelete true
- InlineFix: <nil>
- NewLines: []
 
DEBU [importissue] goimports: pos 13    range <nil>
replacement:
- NeedOnlyDelete false
- InlineFix: <nil>
- NewLines: ['','       "google.golang.org/grpc/codes"','       "google.golang.org/grpc/status"','']

DEBU [importissue] gci diff:
--- github.com/lyft/clutch/backend/middleware/audit/audit.go
+++ github.com/lyft/clutch/backend/middleware/audit/audit.go
@@ -5,8 +5,6 @@
 // <!-- END clutchdoc -->
 
 import (
-       "google.golang.org/grpc/codes"
-       "google.golang.org/grpc/status"
        "context"
        "errors"
        "fmt"
@@ -14,6 +12,8 @@
        "github.com/uber-go/tally"
        "go.uber.org/zap"
        "google.golang.org/grpc"
+       "google.golang.org/grpc/codes"
+       "google.golang.org/grpc/status"
        "google.golang.org/protobuf/proto"
        "google.golang.org/protobuf/types/known/anypb"
  
DEBU [importissue] goimports: pos 8     range 8-9
replacement:
- NeedOnlyDelete true
- InlineFix: <nil>
- NewLines: []
 
DEBU [importissue] goimports: pos 13    range <nil>
replacement:
- NeedOnlyDelete false
- InlineFix: <nil>
- NewLines: ['','       "google.golang.org/grpc/codes"','       "google.golang.org/grpc/status"','']

> Fixer
DEBU [importissue] fixer: Fix issue &result.Issue{FromLinter:"gci", Text:"File is not `gci`-ed with -local github.com/lyft/clutch/backend", Severity:"", SourceLines:[]string{"\t\"google.golang.org/grpc/codes\"", "\t\"google.golang.org/grpc/status\""}, Replacement:(*result.Replacement)(0xc01f0707d0), Pkg:(*packages.Package)(0xc002729b00), LineRange:(*result.Range)(0xc01f0707c0), Pos:token.Position{Filename:"middleware/audit/audit.go", Offset:0, Line:8, Column:0}, HunkPos:0, ExpectNoLint:false, ExpectedNoLintLinter:""} with range 8-9 
DEBU [importissue] fixer: Fix issue &result.Issue{FromLinter:"goimports", Text:"File is not `goimports`-ed with -local github.com/lyft/clutch/backend", Severity:"", SourceLines:[]string{""}, Replacement:(*result.Replacement)(0xc047117210), Pkg:(*packages.Package)(0xc002729b00), LineRange:(*result.Range)(nil), Pos:token.Position{Filename:"middleware/audit/audit.go", Offset:0, Line:13, Column:0}, HunkPos:0, ExpectNoLint:false, ExpectedNoLintLinter:""} with range 13-13 
DEBU [importissue] fixer: Fix issue &result.Issue{FromLinter:"gci", Text:"File is not `gci`-ed with -local github.com/lyft/clutch/backend", Severity:"", SourceLines:[]string{"\t\"google.golang.org/grpc\""}, Replacement:(*result.Replacement)(0xc01f070850), Pkg:(*packages.Package)(0xc002729b00), LineRange:(*result.Range)(nil), Pos:token.Position{Filename:"middleware/audit/audit.go", Offset:0, Line:16, Column:0}, HunkPos:0, ExpectNoLint:false, ExpectedNoLintLinter:""} with range 16-16
```

**Comment by danielhochman** [comment] 2021-03-09 17:42
So far, I'm pretty sure the issue is related to one or all of these code paths:
- [`extractIssuesFromPatch`](https://github.com/golangci/golangci-lint/blob/60613dc3eb841f9d3a07dcc2c59e96eefdfc428f/pkg/golinters/gofmt_common.go#L243), which analyzes the diff from the linter output to determine what the affected lines are and what action is necessary on those lines
- `mergeLineIssues` ([fixer call](https://github.com/golangci/golangci-lint/blob/ef44e11e17f34a397dfaf004e3975b7bbde1322b/pkg/result/processors/fixer.go#L89-L101), [func](https://github.com/golangci/golangci-lint/blob/ef44e11e17f34a397dfaf004e3975b7bbde1322b/pkg/result/processors/fixer.go#L120-L148)), where the fixer tries to merge issues for a file from all the linters that reported together
- `findNotIntersectingIssues` ([fixer call](https://github.com/golangci/golangci-lint/blob/ef44e11e17f34a397dfaf004e3975b7bbde1322b/pkg/result/processors/fixer.go#L103), [func](https://github.com/golangci/golangci-lint/blob/ef44e11e17f34a397dfaf004e3975b7bbde1322b/pkg/result/processors/fixer.go#L186-L207)), where the fixer tries to break fixes up into multiple passes? not 100% sure on that yet

**Comment by thebeline** [comment] 2021-03-27 15:21
@danielhochman, trying to understand:

This is in `fixer.go`, would erroneous behavior in those three functions trigger if I weren't using `--fix`?

**Comment by ldez** [comment] 2021-03-27 15:34
@thebeline yes it's what I say in my comment https://github.com/golangci/golangci-lint/issues/1490#issuecomment-778782810

**Comment by thebeline** [comment] 2021-03-27 15:59
@ldez I can confirm that, if this is related to my closed issues, it doesn't have to do with `gofmt`, `goimports`, `gci`, or `gofumpt`, as the `col` duplication I am seeing still occurs with those shut off.

In fact, if I run with just `unparam` and `unused`, I am seeing a `col` duplication of 3 (`ERRORING_LINTER_COUNT+1`, as I had mentioned).

Curiously (if data helps, which I hope it does):
- `dogsled` does not trigger the `typecheck` error, so I get no errors.
- `unparam` does trigger `typecheck`, but only once, no `col` duplication
- `unused` does trigger `typecheck`, but only once, no `col` duplication
- `unparam` and `dogsled`, `col` duplication of 2
- `unparam` and `unused`, `col` duplication of 3
- `wsl` triggers it's own errors
- `misspell` triggers it's own errors (only one in my test)
- `wsl` + `misspell` trigger their own in tandem, no duplication or overwrite (`wsl` errors + the one `misspell`)
- `unparam` + `misspell` gets `col` duplication of 3, all `typecheck` (**however**, no error at the `col` that `misspell` had errored on before)

If I were to describe the behavior I am seeing, I would describe it as:
- There is a subset of errors trample all other errors
- If these errors trigger and there is one linter running, it behaves as normal
- If you have `N` linters running, and `E` error, it will not display the other errors, but will duplicate it's own error `E+1` times.

You are more familiar, but off the top of my head it seems like something to do with the `metalinter`?  The consolidation of lint tasks?

I haven't dug in to it to have a more educated guess, just wanted to provide you with some data.

**Comment by ldez** [comment] 2021-03-27 16:24
the fixer is only used when `--fix` is called.

edit: I removed my previous comment because I misread your comment.

**Comment by thebeline** [comment] 2021-03-27 16:39
> the fixer is only used when `--fix` is called.
> 
> edit: I removed my previous comment because I misread your comment.

In which case, ass all functions you mentioned are in `fixer.go` I am not sure the behaviour is related.

I have to do some more research, but I did notice some very strange behaviour when I started doing A/B tests.

I'll have a nice little spreadsheet for you tomorrow. :-)

**Comment by ldez** [comment] 2021-03-27 16:49
Ok so I think it's off-topic, you can continue in #1874

**Comment by sheldonhull** [comment] 2021-09-29 20:49
I recently ran into this as well, and finally found this issue. Thought I was conflicting with other tooling but I've confirmed this behavior is occurring directly when invoked. I tried running `golangci-lint run --fix --enable gci,gofumpt --fast --allow-parallel-runners=false` to see if it would help with duplicates but no results. Will have to revert to manually invoking commands.

**Comment by nightlyone** [comment] 2022-05-19 17:52
Hi @ldez isnt this fixed by PR #2653?

After merging PR #2653 both linters should be compatible.

**Comment by ldez** [comment] 2022-05-19 20:00
no #2653 will not fix this issue. Since v1.45.0, the support of the autofix with gci has been dropped. #2653 just restore the previous behavior and then the bug.

**Comment by Lpaydat** [comment] 2022-10-03 09:13
I'm not sure if this will help you all, but I added the mentioned flags to the VSCode settings and the warning has gone away.

```json
  "go.lintTool": "golangci-lint",
  "go.lintFlags": ["--skip-generated", "-s standard,default"]
```

**Comment by kluevandrew** [comment] 2022-11-17 20:41
Same for me, but i don't have any small example app

**Comment by Crocmagnon** [comment] 2023-07-21 16:33
@ldez 
> gci + gofumpt 	OK

I'm getting conflicts between these two in version 1.53.3

```
golangci-lint run --disable-all --enable gci,gofumpt --fix
```

in:
```go
import (
	"github.com/Crocmagnon/snippetbox/ui"
	"net/http"
)
```

out:
```go
import (
	"net/http"

	"net/http"

	"github.com/Crocmagnon/snippetbox/ui"
)
```

**Comment by Antonboom** [comment] 2023-10-01 08:46
Can `golangci-lint` throw a warning if user enable intersecting linters?

For example, I see no reason to use `goimports` when there is a more advanced `gci`.
Except with `--enable-all`.

**Comment by jalaziz** [comment] 2023-11-19 03:20
Running into this issue as well 😞. It seems like the correct thing to do here is to enforce an ordering of linters. `gci` recommends running `goimports` before `gci`.

Unfortunately, it doesn't seem like there's a way to enforce linter ordering with `golangci-lint`.

**Comment by piepmatz** [comment] 2024-04-26 10:15
Workaround:
golangci-lint [v1.57.0](https://github.com/golangci/golangci-lint/releases/tag/v1.57.0) introduced the `--enable-only` flag (https://github.com/golangci/golangci-lint/pull/4438).
After fixing only the imports first (e.g. using `gci`), the next run with the usual config works.

```
golangci-lint run --enable-only gci --fix
golangci-lint run --fix
```

**Comment by sheldonhull** [comment] 2024-04-26 17:52
What I do is disable both of those and use gofumpt only as it includes import sort already try that and maybe you'll no longer have a competing format.

**Comment by therearesomewhocallmetim** [comment] 2024-10-17 11:27
I'm still having this issue with `golangci-lint v1.61.0`. Is there any workaround or fix?

**Comment by bombsimon** [comment] 2024-10-17 11:51
> I'm still having this issue with `golangci-lint v1.61.0`. Is there any workaround or fix?

Yeah the issue is still open so still active. A workaround is mentioned in https://github.com/golangci/golangci-lint/issues/1490#issuecomment-2079080064

**Closed** 2024-12-17 22:22 UTC
Labels: bug

**Comment by sitano** [comment] 2025-11-26 16:27
Just reordering formatters with --enable-only is not a solution because it will be breaking files modification dates all the time. I wrote a patch to gofumpt if anyone interested. See 6214.
