### ISSUE TITLE
bodyclose: panic "interface conversion: interface {} is nil, not *buildssa.SSA"

### ISSUE THREAD

**Issue by vahid-sohrabloo** [golangci/golangci-lint#3086] opened 2022-08-09 18:45 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

I ran the linter on the chconn repo
https://github.com/vahid-sohrabloo/chconn
```
ERRO [runner] Panic: bodyclose: package "column" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: interface {} is nil, not *buildssa.SSA: goroutine 4598 [running]:
 ```

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.48.0 built from 2d8fea81 on 2022-08-04T18:44:38Z
```

</details>

### Configuration file

<details>
https://github.com/vahid-sohrabloo/chconn/blob/master/.golangci.yml
</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.19 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vahid/.cache/go-build"
GOENV="/home/vahid/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vahid/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vahid/go/"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/vahid/projects/chconn/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4032773505=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /home/vahid/projects/chconn /home/vahid/projects /home/vahid /home /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [lintersdb] Active 34 linters: [bodyclose deadcode depguard dogsled dupl errcheck exhaustive exportloopref funlen gochecknoinits goconst gocyclo gofmt goimports goprintffuncname gosec gosimple govet ineffassign lll misspell nakedret noctx nolintlint rowserrcheck staticcheck structcheck stylecheck typecheck unconvert unparam unused varcheck whitespace] 
INFO [loader] Go packages loading at mode 575 (name|types_sizes|deps|exports_file|files|imports|compiled_files) took 179.300672ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 10.870585ms 
INFO [linters context/goanalysis] analyzers took 16.87277408s with top 10 stages: buildir: 4.849183866s, buildssa: 812.739013ms, exhaustive: 546.392954ms, goimports: 339.224849ms, dupl: 337.786451ms, ctrlflow: 330.048343ms, S1038: 286.6035ms, printf: 271.590213ms, inspect: 250.197768ms, gosec: 239.14859ms 
ERRO [runner] Panic: bodyclose: package "column" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: interface {} is nil, not *buildssa.SSA: goroutine 4365 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:101 +0x155
panic({0xf60400, 0xc008742030})
	runtime/panic.go:884 +0x212
github.com/timakin/bodyclose/passes/bodyclose.runner.run({0xc005c0e0d0, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0, 0x0}, 0xc005c0e0d0)
	github.com/timakin/bodyclose@v0.0.0-20210704033933-f49887972144/passes/bodyclose/bodyclose.go:45 +0x697
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc003058240)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:187 +0x9d6
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:105 +0x1d
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc001812eb0, {0x109e6c7, 0x9}, 0xc002f01748)
	github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x4a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc002f017d0?)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:104 +0x85
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc003058240)
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb4
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1eb 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: bodyclose: package "column" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: interface {} is nil, not *buildssa.SSA 
WARN [linters context] rowserrcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters context] structcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
INFO [runner] processing took 3.818µs with stages: max_same_issues: 694ns, skip_dirs: 424ns, nolint: 375ns, max_from_linter: 315ns, cgo: 184ns, skip_files: 177ns, filename_unadjuster: 175ns, path_prettifier: 173ns, uniq_by_line: 170ns, max_per_file_from_linter: 164ns, autogenerated_exclude: 163ns, exclude: 162ns, sort_results: 96ns, source_code: 88ns, path_shortener: 82ns, identifier_marker: 80ns, severity-rules: 77ns, diff: 75ns, exclude-rules: 72ns, path_prefixer: 72ns 
INFO [runner] linters took 2.283858849s with stages: goanalysis_metalinter: 2.283777236s, rowserrcheck: 10.856µs, structcheck: 8.397µs 
ERRO Running error: 1 error occurred:
	* can't run linter goanalysis_metalinter: goanalysis_metalinter: bodyclose: package "column" (isInitialPkg: true, needAnalyzeSource: true): interface conversion: interface {} is nil, not *buildssa.SSA
 
INFO Memory: 26 samples, avg is 302.5MB, max is 478.0MB 
INFO Execution took 2.485115988s   
```

</details>

### Code example or link to a public repository

<details>

https://github.com/vahid-sohrabloo/chconn

</details>

**Comment by pellared** [comment] 2022-11-05 09:16
This is most likely fixed via dep bumps when I look at https://github.com/golangci/golangci-lint/blob/master/go.mod and https://github.com/timakin/bodyclose/issues/38#issuecomment-1304323617

I think it is worth to retest.

FYI @ldez

**Comment by jaredallard** [comment] 2023-02-08 21:02
We're also hitting this on `v1.51.1`. Let me know if I can provide anything useful here.

**Comment by Antonboom** [comment] 2023-02-20 18:13
+1

And for `ent` too.

`skip-dirs` in `.golangci.yml` doesn't help

**Comment by Antonboom** [comment] 2023-02-22 07:27
@pellared, hi!

I think there is a `x/tools` issue, not only `bodyclose`.

I created a demo and grep list of broken linters:
https://github.com/Antonboom/golangci-vs-ent-generics/blob/main/.golangci.yml#L20

Looks like it's worth renaming the current issue (or create the new one) and making the issue in `golang.org/x/tools`.
Or try to find some workaround on `golangci-lint` side.

(cc) @ldez

**Comment by Antonboom** [comment] 2023-03-17 20:37
@ldez Hello!

When to expect the new `golangci-lint` realse?
Looking forward to updated `x/tools` dependency 🙂

**Comment by ldez** [comment] 2023-03-17 22:31
@Antonboom it is coming :smile: I wanted to wait for gocritic (because I was aware of a current rework) and time to review one other PR.
Now the new version of gocritic is here, and I reviewed the PR.
I will prepare the new release.

**Comment by Antonboom** [comment] 2023-03-19 12:09
@ldez Hi!

I tested `v1.52.0` release and faced with the strange behaviour.

Some of the broken linters now are ok, but some of the linters are still errored.

The last [list](https://github.com/Antonboom/golangci-vs-ent-generics/blob/main/.golangci.yml) of bad linters:
```yml
    - asciicheck
    - bodyclose
    - bidichk
    - contextcheck
    - cyclop
    - decorder
    - depguard
    - dupl
    - dupword
    - errorlint
    - gocyclo
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - nilnil
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - tparallel
    - unparam
```

Current [list](https://github.com/Antonboom/golangci-vs-ent-generics/blob/golangci-lint-v1.52.0/.golangci.yml) of "bad" linters:
```yml
    # Error `interface {} is nil, not *buildssa.SSA`
    - bodyclose           # go 1.12, x/tools v0.2.0
    - contextcheck     # go 1.20, x/tools v0.7.0
    - nilerr                   # go 1.15, x/tools v0.0.0-20201023174141-c8cfbd0f21e6 
    - rowserrcheck     # go 1.13, x/tools v0.1.11 
    - unparam             # go 1.19, x/tools v0.7.0

    # Error `ent.withHooks$1: cannot convert *t0 (M) to PM`
    - noctx                   # go 1.20, x/tools v0.7.0
    - sqlclosecheck    # go 1.19, x/tools v0.5.0
    - tparallel               # go 1.20, x/tools v0.7.0
    - wastedassign      # go 1.14, , x/tools v0.7.0
```

Do you have any ideas? What unites them? Are there any patterns? Which side is the problem on?

P.S. Maybe on the side of golangci-lint not to do the analysis in principle for directories marked as `skip-dirs`?

**Comment by ldez** [comment] 2023-03-19 12:29
Remender that we use only one version of x/tools and we don't care about the go version inside the linters so your matrix is off-topic.
`skip-dirs` is a post-process, so the directories are analyzed.

**Comment by Antonboom** [comment] 2023-03-19 12:38
> so your matrix is off-topic.

yep, I just tried to find some corners cases of MVS process 🤷‍♂️ 

>  is a post-process, so the directories are analyzed.

yes, but not pre-process? :)

**Comment by ldez** [comment] 2023-03-19 13:02
MVS is this simple case that cannot have a problem, it's not npm.

I was trapped, I was thinking that you have tried the impact of the upgrade of x/tools, so I trusted you.
The update doesn't fix this issue.

I already spend some time on this issue (I keep it open in my browser since it was opened).
The idea of a bug inside x/tools was pleasant but for now, we don't find the exact root cause.

**Comment by Antonboom** [comment] 2023-03-19 15:11
Let me add some clarity.

Remember I wrote [above](https://github.com/golangci/golangci-lint/issues/3086#issuecomment-1439549234) there are two issues:

1. `interface {} is nil, not *buildssa.SSA` from `res := pass.ResultOf[buildssa.Analyzer].(*buildssa.SSA)`
2. `ent.withHooks$1: cannot convert *t0 (M) to PM` from `mutationT, ok := m.(PM)`

Pair `any(m).(PM)` + new `x/tools` should fix **2)** – I tested it with local build twice (how I tested any change, please don't take me for an idiot): on `x/tools` master and after then they created a tag.

But I didn’t say anywhere that this update would save from problem **1)**, although as far as I remember, I stopped seeing it too. Anyway I was surprised when you closed this issue.

Now I surprised, confused and truly don't understand why **1)** error still appears. Moreover, if I clear the cache and repeat the run, I see different results. For example, once I faced the new error `<nil> is not *buildssa.SSA` (different from **1)**):

<details>
<summary>Trace</summary>

```console
ERRO [runner] Panic: noctx: package "ent" (isInitialPkg: true, needAnalyzeSource: true): <nil> is not *buildssa.SSA: goroutine 5088 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:102 +0x108
panic({0x1032b96e0, 0x1400ce83360})
        runtime/panic.go:884 +0x1f4
github.com/sonatard/noctx/reqwithoutctx.NewAnalyzer(0x140046bb860)
        github.com/sonatard/noctx@v0.0.2/reqwithoutctx/ssa.go:27 +0x1a8
github.com/sonatard/noctx/reqwithoutctx.Run(0x140012b4ce8?)
        github.com/sonatard/noctx@v0.0.2/reqwithoutctx/main.go:8 +0x20
github.com/sonatard/noctx.run(0x1032fab20?)
        github.com/sonatard/noctx@v0.0.2/noctx.go:30 +0x78
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0x140025fe620)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:188 +0x94c
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:106 +0x20
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0x14000643630, {0x102fca49d, 0x5}, 0x140012b4f30)
        github.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x44
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0x1400da39688?)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:105 +0x74
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0x140025fe620)
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb0
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
        github.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x17c 
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: noctx: package "ent" (isInitialPkg: true, needAnalyzeSource: true): <nil> is not *buildssa.SSA 
INFO [runner] processing took 2.541µs with stages: max_same_issues: 542ns, nolint: 334ns, skip_dirs: 250ns, autogenerated_exclude: 208ns, cgo: 208ns, max_from_linter: 125ns, source_code: 125ns, diff: 84ns, max_per_file_from_linter: 84ns, sort_results: 84ns, path_prefixer: 83ns, identifier_marker: 83ns, path_prettifier: 42ns, uniq_by_line: 42ns, skip_files: 42ns, exclude: 41ns, filename_unadjuster: 41ns, severity-rules: 41ns, path_shortener: 41ns, exclude-rules: 41ns 
INFO [runner] linters took 6.075075125s with stages: goanalysis_metalinter: 6.075029791s 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: goanalysis_metalinter: noctx: package "ent" (isInitialPkg: true, needAnalyzeSource: true): <nil> is not *buildssa.SSA
```

</details>

---

> The idea of a bug inside x/tools was pleasant

Remember that https://github.com/golang/go/issues/58633 still waiting feedback from `x/tools` author. We needed `v0.7.0` for `any`-cast workaround using.

> but for now, we don't find the exact root cause

I'll try to debug `golangci-lint` run. I worry about
1) different results with different cache status;
2) different affected linters on different versions.

> You insisted on creating a new release when it was not necessary to do this to see that the bug was still present. I'm disappointed.

Please, don't blame me for the new release:
1) I didn't expect you to up the major version without notice (like you usually do).
2) As I wrote above, no one guaranteed the closure of all this issue's problems at once.
3) Anyway, release included reenabled linters and other usefulness - I see no reason to worry.

**Comment by ldez** [comment] 2023-03-19 15:19
> I didn't expect you to up the major version without notice (like you usually do).

Remember that we have been forced to drop the old Team Discussion because Github drop this.
We replaced it with new private Discussions.
https://github.com/orgs/golangci/discussions/51

I created a private announcement 12 hours before the release as usual.
https://github.com/orgs/golangci/discussions/53

> Please, don't blame me for the new release

I don't want to blame you, I'm just disappointed, I should have spent more time validating the impact of the various changes.

**Comment by ldez** [comment] 2023-03-19 15:34
Why did I close the issue?
When I see all your PRs pointing to this issue, I was thinking that you analyzed the bug and find the root cause, it was wrong because your PRs were not really related to this issue, and it's my fault because I don't spend enough time analyzing the situation.
I tested the current branch with chconn (an old local clone used to test this bug), but I was using a non-impacted chconn local clone, so I come to the wrong conclusion.

I'm not the end of the world, I don't like this kind of situation.

**Comment by ldez** [comment] 2023-03-19 15:40
The last point, we will be more strict with this issue:
- we will keep the issue for the error "interface conversion: interface {} is nil, not *buildssa.SSA" only
- you can create another issue for "cannot convert *t0 (M) to PM"
-

**Comment by ldez** [comment] 2023-03-19 17:46
I spend some to analyze once again the problem based on your project.
So now I understand the link between "cannot convert *t0 (M) to PM" and this issue.

**Comment by Antonboom** [comment] 2023-03-19 18:32
@ldez, thank u for your comments.

I feel terribly stupid. I tried to repeat my tests again and I really don't understand how I managed to NOT get the above errors.

I apologize and will try to be more careful, my desire to make `golangci-lint` better does not always lead to good consequences.

I will try to contribute to `x/tools`, if you are interested, pay attention to the [comment](https://github.com/golang/go/issues/58633#issuecomment-1475353950). Thanks

**Comment by ldez** [comment] 2023-03-19 18:32
So I created PR #3710 to improve the output when panic happens inside buildssa.

The error `panic "interface conversion: interface {} is nil, not *buildssa.SSA"` is not relevant to diagnose the real problem or just knowing what the problem is.

**Comment by ldez** [comment] 2023-03-19 18:35
I will close this issue, not because the underlying problem is fixed but just because the issue is too generic, and we will have multiple, not related, problems in this issue.
 
So I recommend opening dedicated issues in the future.

When my PR is merged, I will create a bugfix release (if the team agrees with that)

**Closed by ldez** 2023-03-19 18:35 UTC
Labels: bug, dependencies

**Comment by karelbilek** [comment] 2023-03-20 12:15
Sorry for barking in without understanding the situation.

I am having exactly this issue on new ent. Should I make it as a new issue? It seems related to #3711  .

Should I update /x/tools or something?

It is in both binary releases and if installed from git
