### ISSUE TITLE
go-critic: checkers.init panic with go1.19beta1

### ISSUE THREAD

**Issue by kolyshkin** [golangci/golangci-lint#2922] opened 2022-06-16 18:37 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

When I try to use golangci-lint with go 1.19beta1 in GHA CI, I get:
```
Running [/home/runner/golangci-lint-1.46.2-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
  
  goroutine 1 [running]:
  github.com/go-critic/go-critic/checkers.init.22()
  	github.com/go-critic/go-critic@v0.6.3/checkers/embedded_rules.go:47 +0x4b4
```

### Version of golangci-lint

1.46.2

### Configuration file

not relevant

### Go environment

<details>

```console
$ go env
# paste output here
```
GO111MODULE=""
  GOARCH="amd64"
  GOBIN=""
  GOCACHE="/home/runner/.cache/go-build"
  GOENV="/home/runner/.config/go/env"
  GOEXE=""
  GOEXPERIMENT=""
  GOFLAGS=""
  GOHOSTARCH="amd64"
  GOHOSTOS="linux"
  GOINSECURE=""
  GOMODCACHE="/home/runner/go/pkg/mod"
  GONOPROXY=""
  GONOSUMDB=""
  GOOS="linux"
  GOPATH="/home/runner/go"
  GOPRIVATE=""
  GOPROXY="https://proxy.golang.org,direct"
  GOROOT="/opt/hostedtoolcache/go/1.19.0-beta.1/x64"
  GOSUMDB="sum.golang.org"
  GOTMPDIR=""
  GOTOOLDIR="/opt/hostedtoolcache/go/1.19.0-beta.1/x64/pkg/tool/linux_amd64"
  GOVCS=""
  GOVERSION="go1.19beta1"
  GCCGO="gccgo"
  GOAMD64="v1"
  AR="ar"
  CC="gcc"
  CXX="g++"
  CGO_ENABLED="1"
  GOMOD="/home/runner/work/runc/runc/go.mod"
  GOWORK=""
  CGO_CFLAGS="-g -O2"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-g -O2"
  CGO_FFLAGS="-g -O2"
  CGO_LDFLAGS="-g -O2"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build51[30](https://github.com/opencontainers/runc/runs/6923780174?check_suite_focus=true#step:3:31)76706=/tmp/go-build -gno-record-gcc-switches"
</details>

### Verbose output of running

n/a

### Code example or link to a public repository

See https://github.com/opencontainers/runc/runs/6923780174?check_suite_focus=true

https://github.com/opencontainers/runc/pull/3514

**Comment by ldez** [comment] 2022-06-16 18:50
I tried locally with go1.19beta1, and it works.

IMO it's a duplicate of #2673

**Comment by kolyshkin** [comment] 2022-06-16 23:26
> Hello,
> 
> Have you tried to run [go-critic](https://github.com/go-critic/go-critic/releases) as a binary?

Gocritic is not even enabled (nor do I need it).

Also, the same setup works fine in CI with either go 1.16.x or go 1.17.x.

> I tried locally with go1.19beta1, and it works.

Does not work for me. Here's a complete repro:
```console
[kir@kir-rhat runc]$  go install golang.org/dl/go1.19beta1@latest
go: downloading golang.org/dl v0.0.0-20220609182932-6cd2f0e318f7
[kir@kir-rhat runc]$ go1.19beta1 download
<...skip....>
[kir@kir-rhat runc]$ ln -s /home/kir/go/bin/go1.19beta1 /home/kir/bin/go
[kir@kir-rhat runc]$ which go
~/bin/go
[kir@kir-rhat runc]$ go version
go version go1.19beta1 linux/amd64
[kir@kir-rhat runc]$ golangci-lint run ./...
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
	github.com/go-critic/go-critic@v0.6.3/checkers/embedded_rules.go:47 +0x4b4
[kir@kir-rhat runc]$ golangci-lint version
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
	github.com/go-critic/go-critic@v0.6.3/checkers/embedded_rules.go:47 +0x4b4
```

**Comment by ldez** [comment] 2022-06-16 23:36
> Gocritic is not even enabled (nor do I need it).

go-critic use an init function you cannot be disable that

**Comment by rhcarvalho** [comment] 2022-08-03 10:53
> IMO it's a duplicate of #2673

This also seems like a dup for me.

In case anyone lands here, I managed to use Go 1.19 + golangci-lint v1.47.3 by building from source, see https://github.com/golangci/golangci-lint/issues/2673#issuecomment-1203789279.

**Closed** 2022-08-03 18:53 UTC
Labels: bug

**Comment by gliptak** [comment] 2022-08-03 23:42
https://github.com/go-critic/go-critic/issues/1157
